<a href="https://colab.research.google.com/github/xumeiying/Stats_II/blob/master/Linear_Algebra_lab1_11_XMY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy import linalg as LA

# 1 Matrix Addition and Scalar Multiplication


---




For problems 1-3, find the indicated sums, if possible. 

1. $
\begin{bmatrix}1 & 3 \\5& 0\end{bmatrix}
+ 
\begin{bmatrix}-2 & 0 \\1 & 1\end{bmatrix}
=
\begin{bmatrix}1-2 & 3 +0\\5+1 & 0+1\end{bmatrix}
=
\begin{bmatrix}-1 & 3\\6 & 1\end{bmatrix}
$

<br>

2. 
$\begin{bmatrix}2 & 3\\15 & 7\end{bmatrix}
+
\begin{bmatrix} 1 & 0 & 6 \end{bmatrix}
$ is not conformable. 

<br>

3. 
$
\begin{bmatrix}
2 & 0 & 2\\1 & 3 & 1\\1 & -1 & 4\end{bmatrix}
+
\begin{bmatrix}10&3&4\\1&0&1\\3&0&3\end{bmatrix}
=
\begin{bmatrix}3&3&6\\2&3&2\\4&-1&7\end{bmatrix}
$

<br>

4. Find the matrix A that satisfies the equation $A - 
\begin{bmatrix}0&-1\\0&0\end{bmatrix}
=
\begin{bmatrix}3&-1\\2&1\end{bmatrix}
$.

<br>

$$A = \begin{bmatrix} 3+0 & -1+(-1)\\ 2+0 & 1+0 \end{bmatrix}
=
\begin{bmatrix} 3 & -2\\ 2&1 \end{bmatrix}
$$

<br>

5. Let $ A =  \begin{bmatrix} b & c \\ 2b & 3c^2 \end{bmatrix}$ and $\alpha = 3$, find $\alpha A$.

<br>

$$ \alpha A = \begin{bmatrix} 3b & 3c \\ 6b & 9c^2 
\end{bmatrix} $$

<br>

6. Let $
A = \begin{bmatrix} 1&-2\\ 3b&5 \end{bmatrix}$ and $\alpha = 0.5$, find $\alpha A$.

<br>

$$\alpha A = \begin{bmatrix} 0.5 & -1\\ 1.5 & 2.5 \end{bmatrix}
$$

<br>

7. Let $\alpha - -2$, 
$ A = \begin{bmatrix}3 & -2\\1 & 5\end{bmatrix}$, and $B = \begin{bmatrix} 0 & -1\\ -3 & 5\end{bmatrix} $, find $\alpha (A+B)$ and $\alpha A + \alpha B$

<br>

$$ \alpha (A+B) = (-2) * \begin{bmatrix} 3+0 & -2+1\\1-3 & 5+4 \end{bmatrix}
= (-2) * \begin{bmatrix} 3 & -1\\-1 & 9 \end{bmatrix}
= \begin{bmatrix} -6 & 2\\ 2 & -18 \end{bmatrix}
$$

<br>

$$
\alpha A + \alpha B = (-2) * \begin{bmatrix} 3 & -2\\1 & 5 \end{bmatrix} + (-2) * \begin{bmatrix} 0 & 1\\-3 & 4\end{bmatrix}
=  \begin{bmatrix} -6 & 4\\ -2 & -10 \end{bmatrix} + \begin{bmatrix} 0 & -2\\ 6 & -8\end{bmatrix} = 
\begin{bmatrix} -6 & 2\\-8 & -18 \end{bmatrix}
$$

# 2 Matrix Multiplication

---

1. Expand the equation $c_{ij} = \sum_{k=1}^{n}a_{ik}b_{kj}$ for $i = 1, 2; j = 1, 2, 3;$ and $n = 2$. 

$$c_{11} = a_{11}b_{11} + a_{12}b_{21} $$
$$c_{12} = a_{11}b_{12} + a_{12}b_{22} $$
$$c_{13} = a_{11}b_{13} + a_{12}b_{23} $$
$$c_{21} = a_{21}b_{11} + a_{22}b_{21} $$
$$c_{22} = a_{21}b_{12} + a_{22}b_{22} $$
$$c_{23} = a_{21}b_{13} + a_{22}b_{23} $$



2. Given $u\prime = [5 \ 1 \ 3], v\prime = [3 \ 1 \ -1], w\prime = [7 \ 5 \ 8]$, and $x\prime = [x_{1} \ x_{2} \ x_{3}]$, write our the column vectors $u, v, w, x$ and find the following products.

<center>

The column vectors are $u = \begin{bmatrix} 5 \\ 1\\3 \end{bmatrix}$, $v = \begin{bmatrix} 3 \\ 1\\ -1 \end{bmatrix}$, $w = \begin{bmatrix} 7 \\ 5 \\ 8 \end{bmatrix}$, $x = \begin{bmatrix} x_{1} \\ x_{2} \\ x_{3} \end{bmatrix} $.

<br>

a. $u_{(3*1)} v\prime_{(1*3)} = \begin{bmatrix} 15&3&9 \\ 5&1&3\\-5&-3&-3 \end{bmatrix} $

<br>

b. $x_{(3*1)} x\prime_{(1*3)} = \begin{bmatrix} x_{1}x_{1}&x_{2}x_{1}&x_{3}x_{1} \\ x_{1}x_{2}&x_{2}x_{2}& x_{3}x_{2} \\ x_{1}x_{3} & x_{2}x_{3} & x_{3}x_{3} \end{bmatrix} $

<br>

c. $u\prime_{(1*3)} v_{(3*1)} = 15 + 1-3 = 13$

<br>

d. $u\prime_{(1*3)} u_{(3*1)} = 25 + 1 + 9 = 35$



3. Find the following products, if possible.

<br>

a. $\begin{bmatrix} 1&2&-1\end{bmatrix} \times \begin{bmatrix} 1&3\end{bmatrix}$ is not conformable.

<br>

b. $\begin{bmatrix} 3&2&1\\ 0&1&-1 \end{bmatrix} \times \begin{bmatrix} -1&0 \\ 1&-3 \\ 2&4 \end{bmatrix} = \begin{bmatrix} -3+2+1 & 0-6+4 \\ 0-1+1 & 0-3-4 \end{bmatrix} = \begin{bmatrix} 0 & -2 \\ 0 & -78 \end{bmatrix}$

<br>

c. $\begin{bmatrix} 1&-1&2\\ 0&2&1\\1&0&3 \end{bmatrix} \times \begin{bmatrix} -2&0&-1\\ 0&1&1\\-1&2&1\end{bmatrix} = \begin{bmatrix} -2+0-2 & 0-1+4 & -1-1+2 \\ 0+0-1&0+2+2&0-2+1 \\ -2+0-3&0+0+6&-1+0+3 \end{bmatrix} =  \begin{bmatrix} -4 & 3 & 0 \\ -1 & 4 &-1 \\ -5 & 6 & 2 \end{bmatrix} $

<br>

d. $\begin{bmatrix} 1&4&7\\ 2&5&8\\3&6&9 \end{bmatrix} \times \begin{bmatrix} 1&0&0\\ 0&1&0\\0&0&1\end{bmatrix} = \begin{bmatrix}  1&4&7\\ 2&5&8\\3&6&9  \end{bmatrix} I =  \begin{bmatrix}  1&4&7\\ 2&5&8\\3&6&9  \end{bmatrix} $


4. Let $A = \begin{bmatrix} 1&0&2\\ 3&1&0 \end{bmatrix}$ and $B = \begin{bmatrix} -1&-3\\ 0&-1\\-2&0 \end{bmatrix}$. 

a. Find $AB$ and $BA$. Are they the same?

$$ A_{2\times 3}B_{3\times 2} = \begin{bmatrix} -1-4&-3\\ -3&-9-1 \end{bmatrix} =  \begin{bmatrix} -5&-3 \\ -3&-10 \end{bmatrix} $$

$$ B_{3\times 2}A_{2\times 3} = \begin{bmatrix} -1-9&-3&-2 \\ -3&-1&0 \\ -2&0&-4 \end{bmatrix} =  \begin{bmatrix} -10&-3&-2 \\ -3&-1&0 \\ -2&0&-4 \end{bmatrix} $$

$AB$ and $BA$ are not the same.

<br>

b. What is the trace of $AB$? What is the trace of $BA$? Are they the same?

The trace of an $n \times n $ matrix $A$ is defined as $Tr(a) = \sum_{i=1}^{n}a_{ii}$. It is the sum of all the diagonal elements

$$Tr(AB) = -5 - 10 = -15$$
$$Tr(BA) = -10 - 1 - 4 = -15 $$

They are not the same either. 

5. Let $ A = \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix}$, $ B = \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}$, and $ C = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix}$. Find $(A+B)C$ and $AC+BC$. Find $C(A +B)$ and $CA + CB$. What properties of matrix multiplication do the results support?

$$(A+B)C = (\begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}) \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -2&0&-2\\-2&0&-2 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -4&0\\-4&0 \end{bmatrix} $$
<br>
$$AC+BC = \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -8&8\\-23&20 \end{bmatrix} + \begin{bmatrix} 12&-8\\27&-20 \end{bmatrix} = \begin{bmatrix} 4&0\\4&0 \end{bmatrix} $$
<br>
$$C(A+B) = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times (\begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix})  = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \begin{bmatrix} -2&0&-2\\-2&0&-2 \end{bmatrix} = \begin{bmatrix} -4&0&-4\\-2&0&-2 \\ 0&0&0\end{bmatrix} $$
<br>
$$CA+CB = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}  = \begin{bmatrix} -2&4&-6\\-12&14&-15 \\ 0&0&0 \end{bmatrix} + \begin{bmatrix} 6&-4&2\\15&-14&13\\0&0&0 \end{bmatrix} = \begin{bmatrix} 4&0&-4\\3&0&-2\\0&0&0 \end{bmatrix} $$
<br>
This operation shows that the commutative property of multiplication that holds in algebra does not holds for matrix. 

6. Let $I$ be a 3 by 3 identity matrix. Find $I^2$, $I^3$, and $I^4$. What is another name for this kind of matrix?. 

$$I = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^2 = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^3 = I^2 \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^4 = I^3 \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$

They are all identity matrices.

# 3 Determinants


---

Use the expansion-by-cofactor method (_Green and Carroll, 60-63_) to find the determinants of the following matrices. Then use the definition of a determinant to check your answers.

- Cofactor across the $i^{th}$ column: $det A: a_{i1}c_{i1} + \cdots a_{in}c_{in} $.

- Cofactor across the $j^{th}$ row: $det A: a_{1j}c_{1j} + \cdots a_{nj}c_{nj} $.

## Detrminants of $2 \times 2$ matrix

<br>

1. $ det \begin{vmatrix} 1&2\\ 4&4 \end{vmatrix} = 1\times 4 - 2 \times 4 =-4 $

<br>

2.  $ det \begin{vmatrix} 5&0\\ 0&6 \end{vmatrix} = 30 $

<br>

3.  $ det \begin{vmatrix} 0&8\\ 0&9 \end{vmatrix} = 0 $

<br>

4.  $ det \begin{vmatrix} 7&5\\ 0&0 \end{vmatrix} = 0 $

<br>

5.  $ det \begin{vmatrix} 3&x\\ 2&1 \end{vmatrix} = 3-2x $


## Detrminants of $3 \times 3$ matrix
<br>

6. $ det \begin{vmatrix} 1&2&3\\ 0&0&4\\5&6&7 \end{vmatrix} = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 0 +0 +4 \times (-1)^{(2+3)} \times  det \begin{vmatrix} 1&2\\ 5&6 \end{vmatrix} = -4 \times (6-10) = 16 $

<br>

7. $ det \begin{vmatrix} 2&0&-1\\ 3&4&1\\5&0&6 \end{vmatrix} = a_{12}c_{12} + a_{22}c_{22} + a_{32}c_{32} = 0 + 4 \times (-1)^{(2+2)} \times  det \begin{vmatrix} 2&-1\\ 5&6 \end{vmatrix} + 0  = 4 \times (12+5) = 68$

## Detrminants of high-D matrix
<br>

8. $ det \begin{vmatrix} 2&3&5&1\\ 7&0&1&-2\\-1&4&9&2\\3&1&0&4 \end{vmatrix} \\ = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} \\ = 7 \times (-1)^{(2+1)} \times det \begin{vmatrix} 2&5&1\\-1&9&2\\3&0&4 \end{vmatrix} + 0 + 1 \times (-1)^{(2+3)} \times det \begin{vmatrix} 2&3&1\\-1&4&2\\3&1&4 \end{vmatrix} +  2 \times (-1)^{(2+4)} \times det \begin{vmatrix} 2&3&5\\-1&4&9\\3&1&0 \end{vmatrix} \\ = -7 \times (2 \times (-1)^{(1+3)} \times det \begin{vmatrix} 5&1\\9&2 \end{vmatrix} + 4 \times (-1)^{(3+3)} \times det \begin{vmatrix} 2&5\\1&9 \end{vmatrix}) - (2 \times (-1)^{(1+1)} \times det \begin{vmatrix} 4&2\\1&4 \end{vmatrix}+ 3 \times (-1)^{(1+2)} \times det \begin{vmatrix} -1&2\\3&4 \end{vmatrix} + (-1)^{(1+3)} \times det \begin{vmatrix} -1&4\\3&1 \end{vmatrix})+ 2 \times (3 \times (-1)^{(1+3)} \times det \begin{vmatrix} 3&5\\4&9 \end{vmatrix} + (-1)^{(3+2)} \times det \begin{vmatrix} 2&5\\-1&9 \end{vmatrix}) \\ =-7 \times [(-2)+5\times 13] - [2\times 14 -3\times (-10)+-14] + 2\times[3\times 7-23]\\ = (-7)\times 63 - 44 -4 = -489 $ 

In [0]:
# check answers
LA.det(np.matrix([[2,3,5,1],
                 [7,0,1,-2],
                 [-4,1,9,2],
                 [3,1,0,4]]))

-742.0

9. $det \begin{vmatrix} 1&3&2&0&4\\7&9&0&4&1\\5&8&0&3&2\\1&5&7&0&6\\-1&3&2&1&5 \end{vmatrix}
= 2 \times det \begin{vmatrix} 7&9&4&1\\5&8&3&2\\1&5&0&6\\-1&3&1&5\end{vmatrix} - 7 \times det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\-1&3&1&5\end{vmatrix} + 2\times det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\1&5&0&6\end{vmatrix} \\
$

<br>

$det \begin{vmatrix} 7&9&4&1\\5&8&3&2\\1&5&0&6\\-1&3&1&5\end{vmatrix} = det \begin{vmatrix} 9&4&1\\8&3&2\\3&1&5 \end{vmatrix} - 5\times det \begin{vmatrix} 7&4&1\\5&3&2\\-1&1&5\end{vmatrix}  - 6\times det \begin{vmatrix} 7&9&4\\5&8&3\\-1&3&1\end{vmatrix}\\
= 9*3*8+4*2*3+1*8*2-4*8*5-1*2*9-1*3*1 - 5\times (7*3*5-4*2*1+1*5*2-4*5*5-1*2*7+1*3*1) - 6\times(7*8-3*9+4*5*3-5*9-3*3*7+4*8)\\
= 75 - 5\times (-4)-  6\times(13) \\
=13 $

<br>

$det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\-1&3&1&5\end
{vmatrix} \\
= det \begin{vmatrix} 9&4&1\\8&3&2\\-3&1&5\end{vmatrix} -3\times det \begin{vmatrix} 7&4&1\\5&3&2\\-1&1&5\end{vmatrix} - 4\times det \begin{vmatrix} 7&9&4\\5&8&3\\-1&3&1\end{vmatrix}\\
= (9*3*4-4*2*3+8-4*5*8-2*9+3*3)-3\times (7*3*5-4*2+5-4*5*5-2*7+3) - 4\times (7*8-3*9+4*5*5-5*9-3*3*7+4*8)\\
= -77 -3\times(-9) - 4\times(53)\\
=-262 $

<br>

$det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\1&5&0&6\end{vmatrix}\\
= -4\times det \begin{vmatrix} 1&3&4\\5&8&2\\1&5&6\end{vmatrix} + 3\times det \begin{vmatrix} 1&3&4\\7&9&1\\1&5&6\end{vmatrix}\\
= -4\times(8*6+3*2+4*5*5-3*6*5-2*5-4*8)+3\times(9*6+3+4*7*5-6*7*3-5-4*9)\\
=-4\times 22 + 3\times 30\\
=2$

<br>

Therefore , 
$det \begin{vmatrix} 1&3&2&0&4\\7&9&0&4&1\\5&8&0&3&2\\1&5&7&0&6\\-1&3&2&1&5 \end{vmatrix} = 2\times 13 -7\times(-262) +2\times2 = $


In [0]:
 round(LA.det(np.matrix([[1,3,2,0,4],
                 [7,9,0,4,1],
                 [5,8,0,3,2],
                 [1,5,7,0,6],
                 [-1,3,2,1,5]])),1)

213.0

# 4 Properties of Inverse Matrices

---



Let $A$ and $B$ be 3 by 3 matrics such that $A = \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix}$, and $B = \begin{bmatrix} 1&2&1\\2&3&0\\1&3&0\end{bmatrix}$. 



<br>

## 1. Show that $(A^{-1})^{-1} = A$. 
<br>

$adj(A) =  \begin{bmatrix}  0 &(-1)\times (12-6)& 0\\(-1)\times (3-0)&24-18&(-1)\times (0-6)\\1&(-1)\times (8-12)& (0-4) \end{bmatrix} \prime  = \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4 \end{bmatrix} \prime = \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4 \end{bmatrix} $

<br>

$det(A) = 0+6+0 - 12 - 0-0 = -6$

<br>

$A^{-1} = \frac{1}{det(A)} adj(A) = (- \frac{1}{6}) \times \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4 \end{bmatrix} = \begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}  $

<br>

$adj(A^{-1}) = \begin{bmatrix}  -\frac{4}{3} &-\frac{2}{3}& -1\\-\frac{1}{6}&0&0 \\ -\frac{1}{2}&-\frac{1}{6}& - \frac{1}{2} \end{bmatrix} \prime = \begin{bmatrix}  -\frac{4}{3} &-\frac{1}{6}& -\frac{1}{2}\\-\frac{2}{3}&0&-\frac{1}{6} \\ -1 &0& - \frac{1}{2} \end{bmatrix} $

<br>

$det(A^{-1}) = \frac{1}{6}-(\frac{1}{3})=-\frac{1}{6}$

<br>

$(A^{-1})^{-1}= \frac{1}{det(A^{-1})}adj(A^{-1}) = (-6) \times \begin{bmatrix}  -\frac{4}{3} &-\frac{1}{6}& -\frac{1}{2}\\-\frac{2}{3}&0&-\frac{1}{6} \\ -1 &0& - \frac{1}{2} \end{bmatrix} =  \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix} =  A$

In [0]:
# check answer
A = np.matrix([[8,1,3],
              [4,0,1],
              [6,0,3]])
inv_A = LA.inv(A)

print("inv(A)= \n", 
      np.around(inv_A, decimals=3))

print("\n inv(inv(A))= \n", np.around(LA.inv(inv_A), decimals=3))

inv(A)= 
 [[-0.     0.5   -0.167]
 [ 1.    -1.    -0.667]
 [ 0.    -1.     0.667]]

 inv(inv(A))= 
 [[8. 1. 3.]
 [4. 0. 1.]
 [6. 0. 3.]]



## 2. Show that $(AB)^{-1}=B^{-1}A^{-1}$.

$AB = \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix} \times \begin{bmatrix} 1&2&1\\2&3&0\\1&3&0\end{bmatrix} = \begin{bmatrix} 8+2+3&16+3+9&8\\4+1&8+3&4\\6+3&12+9&6\end{bmatrix} = \begin{bmatrix} 13&28&8\\5&11&4\\9&21&6\end{bmatrix}$

<br>

$det(AB) = 13*11*6 + 28*4*9 + 8*5*21 - 28*5*6 - 13*4*21-8*11*9 = -18$

<br>

$adj(AB) = \begin{bmatrix} 11*6-4*21&-(5*6-4*9)&21*5-9*11\\-(6*28-8*21)&6*13-9*8&-(21*13-9*28)\\4*28-8*11&-(4*13-5*8)&11*13-5*28\end{bmatrix} \prime \\
= \begin{bmatrix} -18&6&6\\0&6&-21\\24&-12&3\end{bmatrix} \prime = \begin{bmatrix} -18&0&24\\6&6&-12\\6&-21&3\end{bmatrix} $

<br>

$(AB)^{-1} = \frac{1}{det(AB)} adj(AB) = - \frac{1}{18} \times \begin{bmatrix} -18&0&24\\6&6&-12\\6&-21&3\end{bmatrix} = \begin{bmatrix} 1&0&- \frac{4}{3} \\- \frac{1}{3} &- \frac{1}{3} & \frac{2}{3} \\- \frac{1}{3} &\frac{7}{6} &- \frac{1}{6} \end{bmatrix}$


<br>
From #1 we have calculated that $A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$

<br>

$det(B) = 0+0+0-0-0-3 = 3$
$adj(B) = \begin{bmatrix} 0-0&-(0-0)&6-3\\-(0-3)&0-1&-(2-3)\\0-3&-(0-2)&3-4\end{bmatrix} \prime 
= \begin{bmatrix} 0&0&3\\3&-1&1\\-3&2&-1\end{bmatrix} \prime = \begin{bmatrix} 0&3&-3\\0&-1&2\\3&1&-1\end{bmatrix} $

<br>

$B^{-1} = \frac{1}{det(B)}adj(B) =  \frac{1}{3} \begin{bmatrix} 0&3&-3\\0&-1&2\\3&-1&-1\end{bmatrix} = \begin{bmatrix} 0&1&-1\\0&-\frac{1}{3} &\frac{2}{3} \\1&-\frac{1}{3} &-\frac{1}{3} \end{bmatrix} $

<br>

$B^{-1}A^{-1} = \begin{bmatrix} 0&1&-1\\0&-\frac{1}{3} &\frac{2}{3} \\1&-\frac{1}{3} &-\frac{1}{3} \end{bmatrix} \times \begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix} = \begin{bmatrix} 1&0&-\frac{4}{3}\\-\frac{1}{3} &-\frac{1}{3}&\frac{4}{3} \\-\frac{1}{3}&\frac{7}{6} &-\frac{1}{6} \end{bmatrix} = (AB)^{-1}$

In [0]:
B = np.matrix([[1,2,1],
               [2,3,0],
               [1,3,0]])
print("AB= \n", A*B)
print("\n inv(AB)= \n", np.round(LA.inv(A*B), decimals=2))
print("\n inv(B)inv(A)= \n", np.round(LA.inv(B)* LA.inv(A),decimals=2))

AB= 
 [[13 28  8]
 [ 5 11  4]
 [ 9 21  6]]

 inv(AB)= 
 [[ 1.   -0.   -1.33]
 [-0.33 -0.33  0.67]
 [-0.33  1.17 -0.17]]

 inv(B)inv(A)= 
 [[ 1.    0.   -1.33]
 [-0.33 -0.33  0.67]
 [-0.33  1.17 -0.17]]


## 3. Show that $(A\prime)^{-1}=(A^{-1})\prime$.
$A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$, $(A^{-1})\prime =\begin{bmatrix} 0&1&0\\\frac{1}{2}&-1& -1\\-\frac{1}{6}&-\frac{2}{3} &\frac{2}{3} \end{bmatrix}$. 

<br>

$A\prime = \begin{bmatrix} 8&4&6\\1&0&0\\3&1&3\end{bmatrix}$, $det(A\prime) = 6-12 = -6$

<br>

$adj(A\prime) = \begin{bmatrix} 0&-(3)&1\\-(12-6)&24-18&-(8-12)\\0&-(-6)&-4\end{bmatrix}\prime  = \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4\end{bmatrix}\prime = \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4\end{bmatrix}\prime $

<br>

$(A\prime)^{-1} = \frac{1}{det(A\prime)} adj(A\prime) = -\frac{1}{6} \times \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4 \end{bmatrix} = \begin{bmatrix} 0&1&0\\\frac{1}{2}&-1& -1\\-\frac{1}{6}&-\frac{2}{3} &\frac{2}{3} \end{bmatrix}$.

<br>

$(A\prime)^{-1}=(A^{-1})\prime$ is thus proven.

In [0]:
print("(A_inv)transpose = \n", np.round(LA.inv(A).T, decimals = 2))

print("\n (A_transpose)inv = \n", np.round(LA.inv(A.T), decimals=2))

(A_inv)transpose = 
 [[-0.    1.    0.  ]
 [ 0.5  -1.   -1.  ]
 [-0.17 -0.67  0.67]]

 (A_transpose)inv = 
 [[ 0.    1.    0.  ]
 [ 0.5  -1.   -1.  ]
 [-0.17 -0.67  0.67]]


## 4. Show that $det(A^{-1}) = \frac{1}{det(A)}$.

<br>

From #1, we get $det(A) = 0+6+0 - 12 - 0-0 = -6$. 

<br>

From #3, we get $A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$. We can then calculate $det(A^{-1})= \frac{1}{6} - \frac{1}{3} = -\frac{1}{6}$.

<br>

$det(A^{-1}) = \frac{1}{det(A)}$ is thus proven.
 

## 5. 

Let $C$ be a 3 by 3 matrix such that $C = \begin{bmatrix} 6&2&4\\0&2& 1\\0&0&3 \end{bmatrix}$. Find the inversion of $C$ and verify that it is a triagular matrix. 

A triangular matrix is one that is either lower triangular or upper triangular.

<br>

$det(C) = 6*2*3 - 0 =36$ 

<br>

$adj(C) = \begin{bmatrix} 6&-0&0\\-6&18&-0\\2-8&-6&12 \end{bmatrix} \prime  = \begin{bmatrix} 6&0&0\\-6&18&0\\-6&-6&12 \end{bmatrix} \prime =  \begin{bmatrix} 6&-6&-6\\0&18&-6\\0&0&12 \end{bmatrix}  $

<br>

$C^{-1} = \frac{1}{det(C)} adj(C) = \frac{1}{36} \times \begin{bmatrix} 6&-6&-6\\0&18&-6\\0&0&12 \end{bmatrix} = \begin{bmatrix} \frac{1}{6}&-\frac{1}{6}&-\frac{1}{6}\\0&\frac{1}{2}&-\frac{1}{6}\\0&0&\frac{1}{3} \end{bmatrix}$

<br>

C is shown as a lower triangular matrix.

In [0]:
C = np.matrix([[6,2,4],
               [0,2,1],
               [0,0,3]])
LA.det(C)
LA.inv(C)

matrix([[ 0.16666667, -0.16666667, -0.16666667],
        [ 0.        ,  0.5       , -0.16666667],
        [ 0.        ,  0.        ,  0.33333333]])

# 5 Matrix Inversion

---



## I. Find the inverses of the following matrices, if they exist. Use Mathematica to check your answers.

<br>

1. $\begin{bmatrix}1&2\\3&4\end{bmatrix}$
$$det = 4-6 = -2$$

$$adj = \begin{bmatrix}4&-3\\-2&1\end{bmatrix}$$

$$(\begin{bmatrix}1&2\\3&4\end{bmatrix})^{-1} = -\frac{1}{2} \times \begin{bmatrix}4&-3\\-2&1\end{bmatrix} = \begin{bmatrix}-2&1.5\\1&-0.5 \end{bmatrix}$$

<br>

2. $\begin{bmatrix}5&0\\0&6\end{bmatrix}$

$$det = 30-0 = 30$$

$$adj = \begin{bmatrix}6&0\\0&5\end{bmatrix}$$

$$(\begin{bmatrix}5&0\\0&6\end{bmatrix})^{-1} = \frac{1}{30} \times \begin{bmatrix}6&0\\0&5 \end{bmatrix} = \begin{bmatrix} \frac{1}{5}&0\\0&\frac{1}{6} \end{bmatrix}$$

<br>

3. $\begin{bmatrix}0&8\\0&9\end{bmatrix}$

$det =0$, the matrix is not of full rank and thus not inversable. 

<br>

4. $\begin{bmatrix}7&5\\0&0\end{bmatrix}$

$det =0$, the matrix is not of full rank and thus not inversable. 

<br>

5. $\begin{bmatrix}3&x\\2&1\end{bmatrix}$

$$det = 3-2x$$

$$adj = \begin{bmatrix}1&-2\\-3&x \end{bmatrix}$$

$$(\begin{bmatrix}3&x\\2&1\end{bmatrix})^{-1} = \frac{1}{3-2x} \times \begin{bmatrix}1&-2\\-3&x \end{bmatrix} = \begin{bmatrix} \frac{1}{3-2x}&-\frac{2}{3-2x}\\-\frac{3}{3-2x}&\frac{x}{3-2x}\end{bmatrix}$$

<br>

6. $\begin{bmatrix}1&2&3\\0&0&4\\5&6&7 \end{bmatrix}$

$$det = 2\times 4 \times5 - 1\times 6\times 4 = 16$$

$$adj = \begin{bmatrix}-24&-(-20)&0\\-(14-18)&7-15&-(6-10)\\8&-(4)&0 \end{bmatrix} \prime = \begin{bmatrix}-24&20&0\\-4&-8&4\\8&-4&0 \end{bmatrix} \prime = \begin{bmatrix}-24&-4&8\\20&-8&-4\\0&-4& 0\end{bmatrix}$$

$$(\begin{bmatrix}1&2&3\\0&0&4\\5&6&7 \end{bmatrix})^{-1} = \frac{1}{16} \times \begin{bmatrix}-24&-4&8\\20&-8&-4\\0&-4& 0\end{bmatrix} =  \begin{bmatrix}-1.5&-0.25&0.5\\1.25&-0.5&-0.25\\0&-0.25&0\end{bmatrix}$$

7. $\begin{bmatrix}2&0&-1\\3&4&1\\5&0&6 \end{bmatrix}$

$$det = -4*5-2*4*6 = -68$$

$$adj = \begin{bmatrix}24&-(18-5)&-20\\-(0)&12-(-5)&-(0)\\0-(-4)&-(2-(-3))&8 \end{bmatrix} \prime = \begin{bmatrix}24&-23&-20\\0&17&0\\4&-5&8 \end{bmatrix} \prime = \begin{bmatrix}24&0&4\\-23&17&-5\\-20&0&8 \end{bmatrix}$$

$$(\begin{bmatrix}2&0&-1\\3&4&1\\5&0&6 \end{bmatrix})^{-1} = -\frac{1}{68} \times \begin{bmatrix}24&0&4\\-23&17&-5\\-20&0&8 \end{bmatrix} = \begin{bmatrix} -\frac{6}{17} &0&-\frac{1}{17} \\\frac{23}{68} &\frac{1}{4}&\frac{5}{68}\\\frac{5}{17}&0&- \frac{2}{17} \end{bmatrix}$$

<br>

8. $\begin{bmatrix}1&2&3\\1&3&6\\1&4&10 \end{bmatrix}$

$$det =3*10+ 2*6+ 3*4-2*10-4*6-3*3= 20+12+12-20-24-9 = 1$$

$$adj = \begin{bmatrix}30-24&-(10-6)&4-3\\-(20-12)&10-3&-(4-2)\\12-9&-(6-3))&3-2 \end{bmatrix} \prime = \begin{bmatrix}6&-4&1\\-8&7&-2\\3&-3&1 \end{bmatrix} \prime = \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix}$$

$$(\begin{bmatrix}1&2&3\\1&3&6\\1&4&10 \end{bmatrix})^{-1} = 1\times \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix} = \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix}$$


In [0]:
print("6. \n", LA.inv(np.matrix([[1,2,3],
          [0,0,4],
           [5,6,7]])))

print("\n 7. \n", LA.inv(np.matrix([[2,0,-1],
                  [3,4,1],
                  [5,0,6]])))

print("\n 8. \n", LA.inv(np.matrix([[1,2,3],
                  [1,3,6],
                  [1,4,10]])))

6. 
 [[-1.5   0.25  0.5 ]
 [ 1.25 -0.5  -0.25]
 [ 0.    0.25  0.  ]]

 7. 
 [[ 0.35294118  0.          0.05882353]
 [-0.19117647  0.25       -0.07352941]
 [-0.29411765 -0.          0.11764706]]

 8. 
 [[ 6. -8.  3.]
 [-4.  7. -3.]
 [ 1. -2.  1.]]


## II. Solve the following systems of equations by using matrices. Use Mathematica to check your answers.

<br>

9. $2x-3y =2\\4x+y=5$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}2\\5 \end{bmatrix}$.   

$$ \begin{aligned}
\begin{bmatrix}x\\y \end{bmatrix} 
&= (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}2\\5 \end{bmatrix}\\ 
&= \frac{1}{2*1 - 4*(-3)} \times \begin{bmatrix}1&-4\\3&2 \end{bmatrix} \prime \times \begin{bmatrix}2\\5 \end{bmatrix}  \\ &=  \frac{1}{14} \times \begin{bmatrix}1&3\\-4&2 \end{bmatrix} \times \begin{bmatrix}2\\5 \end{bmatrix} \\
&=  \frac{1}{14} \times \begin{bmatrix}1*2+3*5\\-4*2+2*5 \end{bmatrix}\\
&=  \frac{1}{14} \times \begin{bmatrix}17\\2 \end{bmatrix}\\
&= \begin{bmatrix}\frac{17}{14}\\ \frac{1}{7} \end{bmatrix} \end{aligned}
$$ 

Thus, $x=\frac{17}{14}, y = \frac{1}{7} $

<br>

10. $2x-3y=0\\4x+y=3$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}0\\3 \end{bmatrix}$.  

$$ \begin{aligned}
\begin{bmatrix}x\\y \end{bmatrix} 
&= (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}0\\3 \end{bmatrix}\\ 
&=  \frac{1}{14} \times \begin{bmatrix}1&3\\-4&2 \end{bmatrix} \times \begin{bmatrix}0\\3 \end{bmatrix} \\
&=  \frac{1}{14} \times \begin{bmatrix}9\\6 \end{bmatrix}\\
&= \begin{bmatrix}\frac{9}{14}\\ \frac{3}{7} \end{bmatrix} \end{aligned}$$

Therefore, $x=\frac{9}{14}, y = \frac{3}{7} $
 

<br>

11. $2x-3y=0\\4x+y=0$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}0\\0 \end{bmatrix}$. Thus $ \begin{bmatrix} x\\y \end{bmatrix} = (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}0\\0 \end{bmatrix} = \begin{bmatrix}0\\0 \end{bmatrix} $. Therefore, $x=y=0$

<br>

12. $-3x_{1}- x_{2}-3x_{3}=1 \\ 6x_{1}+x_{2}+3x_{3}=0 \\ 2x_{1}+x_{3}=1$

The linear equations expressee in matrix form is $ \begin{bmatrix}-3&-1&-3\\6&1&3\\2&0&1 \end{bmatrix} \times \begin{bmatrix}x_{1}\\x_{2}\\x_{3} \end{bmatrix} = \begin{bmatrix}1\\0\\1 \end{bmatrix}$.

$$ \begin{aligned}
\begin{bmatrix} x_{1}\\x_{2}\\x_{3} \end{bmatrix} 
&= (\begin{bmatrix}-3&-1&-3\\6&1&3\\2&0&1 \end{bmatrix})^{-1} \times \begin{bmatrix}1\\0\\1 \end{bmatrix}\\ 
&=  \frac{1}{-3-6+0-(-6)-0-(-6)} \times \begin{bmatrix}1&-(0)&-2\\-(-1)&-3-6&-(0-(-2))\\-3-(-3)&-(-9-(-18))&-3-(-6) \end{bmatrix} \prime \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&=  \frac{1}{3} \times \begin{bmatrix}1&0&-2\\1&3&-2\\0&-9&3 \end{bmatrix} \prime \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&= \frac{1}{3} \times \begin{bmatrix}1&1&0\\0&3&-9\\-2&-2&3 \end{bmatrix} \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&= \frac{1}{3} \times \begin{bmatrix}1\\-9\\1 \end{bmatrix}
\\ 
&= \begin{bmatrix}\frac{1}{3}\\-3\\\frac{1}{3} \end{bmatrix}
\end{aligned}$$

Therefore, $x_{1}=frac{1}{3},  x_{2}=-3, x_{3}=frac{1}{3}$.

In [0]:
print("9. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[2],
                                              [5]]))

print("\n 10. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[0],
                                              [3]]))

print("\n 11. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[0],
                                              [0]]))

print("\n 12. \n", 
      LA.inv(np.matrix([[-3,-1,-3],
                        [6,1,3],
                        [2,0,1]])) * np.matrix([[1],
                                                [0],
                                                [1]]))

9. 
 [[1.21428571]
 [0.14285714]]

 10. 
 [[0.64285714]
 [0.42857143]]

 11. 
 [[0.]
 [0.]]

 12. 
 [[ 0.33333333]
 [-3.        ]
 [ 0.33333333]]


matrix([[ 0.33333333,  0.33333333,  0.        ],
        [-0.        ,  1.        , -3.        ],
        [-0.66666667, -0.66666667,  1.        ]])

# 6  Rank of a Matrix

---



## 1. List the three elementary row transformations.

There are three kinds of elementary row matrix operations:
- Interchange two rows $R_{i} \leftrightarrow R_{j}$
- Multiply each element in a row by a non-zero constant $sR_{i} \rightarrow R_{i}$
- Multiply a row by a non-zero constant and add the result to another row $sR_{i} + R_{j} \rightarrow R_{i}$


## 2. What is the echelon form of a matrix?

A matrix is in **row echelon form** ($ref$) when it satisfies the following conditions:
- The first non-zero element in each row, called the leading entry, is 1.
- Each leading entry is in a column to the right of the leading entry in the previous row.
- Rows with all zero elements, if any, are below rows having a non-zero element.

E.g., $\begin{bmatrix}1&2&3&4\\0&0&1&0\\0&0&0&1\\0&0&0&0 \end{bmatrix}$

A matrix is in **reduced row echelon form** ($rref$) when it satisfies the following conditions.
- The matrix satisfies conditions for a row echelon form.
- The leading entry in each row is the only non-zero entry in its _column_.

E.g., $\begin{bmatrix}1&2&0&0\\0&0&1&0\\0&0&0&1\\0&0&0&0 \end{bmatrix}$


## 3. Find the ranks of the following matrices.

### a. 

$$\begin{bmatrix}1&2\\3&4 \end{bmatrix} \xrightarrow{(-3)R_{1} + R_{2}\rightarrow R_{2}} \begin{bmatrix}1&2\\0&-2 \end{bmatrix} \xrightarrow{(-\frac{1}{2})R_{2}\rightarrow R_{2}} \begin{bmatrix}1&2\\0&1 \end{bmatrix} \\ 
\rho(a) = 2
$$

### b. 

$$\begin{bmatrix}5&0\\0&6 \end{bmatrix} \xrightarrow[\frac{1}{6}R_{2} \rightarrow R_{2}] {\frac{1}{5}R_{1} \rightarrow R_{1}} \begin{bmatrix}1&0\\0&1 \end{bmatrix} \\
\rho(b) = 2
$$

### c. 
$$\begin{bmatrix}1&2&3\\0&0&4\\5&6&7 \end{bmatrix} \xrightarrow[\frac{1}{4}R_{2} \rightarrow R_{2}] {R_{3} \leftrightarrow R_{2}} \begin{bmatrix}1&2&3\\5&6&7\\0&0&1 \end{bmatrix} \xrightarrow {(-5)R_{1} + R_{2} \leftrightarrow R_{2}} \begin{bmatrix}1&2&3\\0&-4&-8\\0&0&1 \end{bmatrix} \xrightarrow {(-\frac{1}{4})R_{2} \leftrightarrow R_{2}} \begin{bmatrix}1&2&3\\0&1&2\\0&0&1 \end{bmatrix} 
$$

$$\rho(c) = 3$$

### d. 

$$\begin{bmatrix}2&0&-1\\3&4&1\\5&0&6 \end{bmatrix} \xrightarrow[\frac{1}{3}R_{2} \rightarrow R_{2}] {R_{1} \leftrightarrow R_{2}} \begin{bmatrix}1&\frac{4}{3}&1\\2&0&-1\\5&0&6 \end{bmatrix} 
\xrightarrow [(-5)R_{1} + R_{3} \rightarrow R_{3}]{(-2)R_{1} + R_{2} \rightarrow R_{2}} \begin{bmatrix}1&\frac{4}{3}&1\\0&-\frac{8}{3}&2\\0&-\frac{20}{3}&-5 \end{bmatrix} 
\xrightarrow [(-\frac{3}{20})R_{3} \rightarrow R_{3}]{(-\frac{3}{8})R_{2} \rightarrow R_{2}} \begin{bmatrix} 1&\frac{4}{3}&1\\0&1&-\frac{3}{4}\\0&1&\frac{3}{4}\end{bmatrix} 
\xrightarrow {R_{2} - R_{3} \rightarrow R_{3}} \begin{bmatrix} 1&\frac{4}{3}&1\\0&1&\frac{3}{4}\\0&0&\frac{3}{2}\end{bmatrix}
\xrightarrow {\frac{2}{3}R_{3} \rightarrow R_{3}} \begin{bmatrix} 1&\frac{4}{3}&1\\0&1&\frac{3}{4}\\0&0&1\end{bmatrix}
$$

$$\rho(d) = 3$$

### e. 

$$\begin{bmatrix}1&2&3\\1&3&6\\1&4&0 \end{bmatrix} 
\xrightarrow[R_{2}+(-1)R_{1} \rightarrow R_{2}] {R_{3} +(-1)R_{1}\rightarrow R_{3}} \begin{bmatrix}1&2&3\\0&1&4\\0&2&-3 \end{bmatrix} 
\xrightarrow {(-2)R_{2} + R_{3} \leftrightarrow R_{3}} \begin{bmatrix}1&2&3\\0&1&4\\0&0&-5 \end{bmatrix} 
\xrightarrow {(-\frac{1}{5})R_{3} \rightarrow R_{2}} \begin{bmatrix} 1&2&3\\0&1&4\\0&0&1 \end{bmatrix} 
$$

$$\rho(e) = 3$$

### f. 

$$\begin{bmatrix}1&0&0&5\\0&1&0&4\\0&0&1&3 \end{bmatrix} $$

$$\rho(f) = 3$$

### g. 

$$\begin{bmatrix}0&0&0\\0&0&0\\0&0&0 \end{bmatrix} $$

$$\rho(g) = 0$$

### h. 

$$
\begin{bmatrix}0&1&1&1\\-1&0&1&1\\-1&-1&0&1\\-1&-1&-1&0 \end{bmatrix} 
\xrightarrow[(-1)R_{2} \rightarrow R_{2}] {R_{1} \leftrightarrow R_{2}}
\begin{bmatrix}1&0&-1&-1\\0&1&1&1\\-1&-1&0&1\\-1&-1&-1&0 \end{bmatrix} 
\xrightarrow[R_{1}+R_{3} \rightarrow R_{3}] {R_{1} + R_{4}\rightarrow R_{4}}
\begin{bmatrix}1&0&-1&-1\\0&1&1&1\\0&-1&-1&0\\0&-1&-2&-1 \end{bmatrix} 
\xrightarrow[R_{2}+R_{3} \rightarrow R_{3}] {R_{2} + R_{4}\rightarrow R_{4}}
\begin{bmatrix}1&0&-1&-1\\0&1&1&1\\0&0&0&1\\0&0&-1&0 \end{bmatrix} 
\xrightarrow {(-1)R_{4} \leftrightarrow R_{3}}
\begin{bmatrix}1&0&-1&-1\\0&1&1&1\\0&0&1&0\\0&0&0&1 \end{bmatrix} 
$$

$$\rho(h) = 4$$

In [0]:
print("a. The matrix has", LA.matrix_rank(np.matrix([[1,2],
                                                     [3,4]])), "ranks")

print("b. The matrix has", LA.matrix_rank(np.matrix([[5,0],
                                                     [0,6]])), "ranks")

print("c. The matrix has", LA.matrix_rank(np.matrix([[1,2,3],
                                                     [0,0,4],
                                                     [5,6,7]])), "ranks")

print("d. The matrix has", LA.matrix_rank(np.matrix([[2,0,-1],
                                                     [3,4,1],
                                                     [5,0,6]])), "ranks")

print("e. The matrix has", LA.matrix_rank(np.matrix([[1,2,3],
                                                     [1,3,6],
                                                     [1,4,10]])), "ranks")

print("f. The matrix has", LA.matrix_rank(np.matrix([[1,0,0,5],
                                                     [0,1,0,4],
                                                     [0,0,1,3]])), "ranks")

print("g. The matrix has", LA.matrix_rank(np.matrix([[0,0,0],
                                                     [0,0,0],
                                                     [0,0,0]])), "rank")

print("f. The matrix has", LA.matrix_rank(np.matrix([[0,1,1,1],
                                                     [-1,0,1,1],
                                                     [-1,-1,0,1],
                                                     [-1,-1,-1,0]])), "ranks")

a. The matrix has 2 ranks
b. The matrix has 2 ranks
c. The matrix has 3 ranks
d. The matrix has 3 ranks
e. The matrix has 3 ranks
f. The matrix has 3 ranks
g. The matrix has 0 rank
f. The matrix has 4 ranks


# 7 Vectors, Vector Space, and Linear Independence


---


## Consider the following vectors 

$$\vec{a} = \begin{bmatrix} 1&3&2 \end{bmatrix}$$

$$\vec{b} = \begin{bmatrix} 3&-1&0 \end{bmatrix}$$

$$\vec{c} = \begin{bmatrix} \frac{1}{3}&1&-\frac{5}{3} \end{bmatrix}$$

### 1. Show that the vectors are all orthogonal to each other.

Two vectors are orthogonal when they are perpendicular to each other. i.e. the dot product of the two vectors is zero.

$$\vec{a} \cdot \vec{b} = \begin{bmatrix} 1&3&2 \end{bmatrix} \times  \begin{bmatrix} 3&-1&0 \end{bmatrix} = 1*3 + 3*(-1) +2*0 = 0$$

$$\vec{a} \cdot \vec{c} = \begin{bmatrix} 1&3&2 \end{bmatrix} \times  \begin{bmatrix} \frac{1}{3}&1&-\frac{5}{3}  \end{bmatrix} = 1*\frac{1}{3} + 3*1 +2*(-\frac{5}{3}) = 0
$$

$$\vec{b} \cdot \vec{c} = \begin{bmatrix} 3&-1&0 \end{bmatrix} \times  \begin{bmatrix} \frac{1}{3}&1&-\frac{5}{3}  \end{bmatrix} = 3*\frac{1}{3} + (-1)*1 +0*(-\frac{5}{3}) = 0
$$

## Find a basis for the row space of each of the following matrices. Then express the rows of each matrix as a linear combination of the vectors in the basis which you found for the row space of the matrix.

### 2. 
Reduce the matrix to echelon form:
$$
\begin{bmatrix} 3&4\\1&-1\\5&0 \end{bmatrix}
\xrightarrow[]{R_{1} \leftrightarrow R_{2}}
\begin{bmatrix} 1&-1\\3&-4\\5&0 \end{bmatrix}
\xrightarrow[(-3)R_{1} + R_{2} \rightarrow R_{2} ]{(-5)R_{1} + R_{3} \rightarrow R_{3}}
\begin{bmatrix} 1&-1\\0&-1\\0&5 \end{bmatrix}
\xrightarrow[R_{1} +(-1) R_{2} \rightarrow R_{1} ]{(5)R_{2} + R_{3} \rightarrow R_{3}}
\begin{bmatrix} 1&0\\0&-1\\0&0 \end{bmatrix}
\xrightarrow[]{(-1)R_{2}\rightarrow R_{2}}
\begin{bmatrix} 1&0\\0&1\\0&0 \end{bmatrix}
$$

The basis for the row space is thus $\{(1, 0),(0,1)\}$. Therefore, the linear combination of $\begin{bmatrix} 5\\0 \end{bmatrix}$ can be expressed as $\begin{bmatrix} 5\\0 \end{bmatrix} = 5 \begin{bmatrix} 1\\0 \end{bmatrix} + 0 \begin{bmatrix} 0\\1 \end{bmatrix}$. 

<br>

### 3. 
Reduce the matrix to echelon form:
$$
\begin{bmatrix} 2&1&0\\-1&3&4\\2&8&8 \end{bmatrix}
\xrightarrow[R_{3}+2R_{2} \rightarrow R_{3}]{R_{1}+2R_{2} \rightarrow R_{1}}
\begin{bmatrix} 0&7&8\\-1&3&4\\0&14&16 \end{bmatrix}
\xrightarrow[(-1)R_{2} \leftrightarrow R_{1}]{(-2)R_{1}+R_{3} \rightarrow R_{3}}
\begin{bmatrix} 1&-3&-4\\0&7&8\\0&0&0 \end{bmatrix}
\xrightarrow[]{(\frac{1}{7})R_{2} \rightarrow R_{2}}
\begin{bmatrix} 1&-3&-4\\0&1&\frac{8}{7}\\0&0&0 \end{bmatrix}
\xrightarrow[]{3R_{2}+R_{1} \rightarrow R_{1}}
\begin{bmatrix} 1&0&-\frac{4}{7}\\0&1&\frac{8}{7}\\0&0&0 \end{bmatrix}
$$

The basis for the row space is ${(1, 0, -\frac{4}{7}}, (0,1,\frac{8}{7})$. Therefore, the linear combination of $\begin{bmatrix} 2\\8\\8 \end{bmatrix}$ can be expressed as $\begin{bmatrix} 2\\8\\8 \end{bmatrix} = 2 \begin{bmatrix} 1\\0\\-\frac{4}{7}\end{bmatrix} + 8 \begin{bmatrix} 0\\1\\\frac{8}{7} \end{bmatrix}$. 

<br>

### 4. 
Reduce the matrix to echelon form:
$$
\begin{bmatrix} 5&-1&2\\4&4&-8\\3&1&-2\\2&-2&4 \end{bmatrix}
\xrightarrow[\frac{1}{2}R_{4}]{R_{1}-R_{2} \rightarrow R_{1}, R_{2}-R_{3} \rightarrow R_{2}, R_{3}-R_{4} \rightarrow R_{3}}
\begin{bmatrix} 1&-5&10\\1&3&6\\1&3&6\\1&-1&2 \end{bmatrix}
\xrightarrow[R_{2}-R_{4} \rightarrow R_{2}, R_{1}-R_{2} \rightarrow R_{1}]{R_{3}-R_{2} \rightarrow R_{3}}
\begin{bmatrix} 0&-8&16\\0&4&-8\\0&0&0\\1&-1&2 \end{bmatrix}
\xrightarrow[R_{4} \leftrightarrow R_{1}, \frac{1}{4}R_{2} \rightarrow R_{2}]{R_{1}+2R_{2} \rightarrow R_{1}}
\begin{bmatrix} 1&-1&2\\0&1&-2\\0&0&0\\0&0&0 \end{bmatrix}
$$

The basis for the row space is $\{(1, -1, 2), (0,-1,2)\}$. 

Therefore, the linear combination of $\begin{bmatrix} 5\\-1\\2 \end{bmatrix}$ can be expressed as $\begin{bmatrix} 2\\8\\8 \end{bmatrix} = 5 \begin{bmatrix} 1\\-1\\2 \end{bmatrix} + 6 \begin{bmatrix} 0\\-1\\2 \end{bmatrix}$. 

<br>

### 5. 
Reduce the matrix to echelon form:
$$\begin{bmatrix} 2&-1&3&0&-4\\7&-1&6&2&-9\\5&5&-6&-6&5\\3&1&0&2&-1 \end{bmatrix}
\xrightarrow[R_{2}-R_{3} \rightarrow R_{2}, R_{3}-R_{4} \rightarrow R_{3}]{R_{4}-R_{1} \rightarrow R_{4}}
\begin{bmatrix} 2&-1&3&0&-4\\2&-6&12&-4&-14\\2&4&-6&4&6\\1&2&-3&2&3 \end{bmatrix}
\xrightarrow[2R_{4}-R_{3} \rightarrow R_{4}, R_{1}-R_{2} \rightarrow R_{1}]{\frac{1}{2}R_{3} \rightarrow R_{3}, -R_{2}+R{3} \rightarrow R_{2}}
\begin{bmatrix} 0&5&-9&4&10\\0&10&-18&8&20\\1&2&-3&2&3\\0&0&0&0&0 \end{bmatrix}
\xrightarrow [2R_{1}-R_{2} \rightarrow R_{1}, \frac{1}{10}R_{2} \rightarrow R_{2}]{R_{3} \leftrightarrow R_{1}}
\begin{bmatrix} 1&2&-3&2&3\\0&1&-\frac{9}{5}&\frac{4}{5}&2\\ 0&0&0&0&0\\0&0&0&0&0 \end{bmatrix}
$$

The basis for the row space is $\{(1, 2, -3,2,3), (0,1,-\frac{9}{5}, \frac{4}{5}, -\frac{9}{5})\}$. 

Therefore, the linear combination of $\begin{bmatrix} 2\\-1\\3\\0\\4 \end{bmatrix}$ can be expressed as $\begin{bmatrix} 2\\-1\\3\\0\\4 \end{bmatrix} = 2 \begin{bmatrix} 1\\2\\-3\\2\\3 \end{bmatrix} - 6 \begin{bmatrix} 0\\1\\-\frac{9}{5}\\\frac{4}{5}\\2 \end{bmatrix}$. 


# 8 Eigenvalues and Eigenvectors

---

Find eigenvalues of the following matrices and their associated eigenvectors. Use Mathematica to check your answers.

For a square matrix $A$, an Eigenvector $\vec v$ and Eigenvalue $\lambda$ make this equation true: 
$$A\vec v = \lambda \vec v $$
We can rewrite the equation as follows:
$$A\vec v -  \lambda \vec v = \vec 0\\
(A-\lambda I) \cdot \vec v = \vec 0
$$

where $I$ is the identity matrix of the same dimensions as $A$. Since $\vec v \neq \vec 0 $, to make this equation exists, $\vec v$ has to sit at the null space of the matrix $(A-\lambda I) $. This means that the matrix $(A-\lambda I) $ is not of full rank, or

$$det(A-\lambda I)=0$$

Eigenvectors can be normalized to a vector with length 1.


## 1. $\begin{bmatrix} 2&1\\0&3 \end{bmatrix}$

$$det \begin{vmatrix} \begin{bmatrix} 2&1\\0&3 \end{bmatrix} - \begin{bmatrix} \lambda\\\lambda \end{bmatrix} \cdot \begin{bmatrix} 1&0\\0&1 \end{bmatrix}  \end{vmatrix}= det \begin{vmatrix} 2-\lambda&1\\0&3-\lambda \end{vmatrix} = (2-\lambda)(3-\lambda)=0 $$

Therefore, the two eigenvalues are $\lambda_{1}=2$, $\lambda_{2}=3$. 

- When $\lambda_{1}=2$, 
$\begin{bmatrix} 2-2&1\\0&3-2 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} 0&1\\0&1 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix} =  \begin{bmatrix} 0\\0\end{bmatrix} $, $v_{2}=0 $, and if normalized, $v_{1}^2 + v_{2}^2 = 1 $. Therefore $v_{1}=1$. 

- When $\lambda_{1}=3$, 
$\begin{bmatrix} -1&1\\0&0 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} 0\\0\end{bmatrix} $, so $v_{1}=v_{2} $, and if standardized, $v_{1}^2 + v_{2}^2 = 1 $. We can thus get $v_{1}=v_{2} = \frac{\sqrt2}{2}$ . 

The two standardized eigenvectors are thus $\vec v_{1} = (1, 0)$ and $\vec v_{2} = (\frac{\sqrt2}{2}, \frac{\sqrt2}{2})$. 

<br>

## 2. $\begin{bmatrix} 0&0\\0&0 \end{bmatrix}$

$$ det \begin{vmatrix} 0-\lambda&0\\0&0-\lambda \end{vmatrix} = (-\lambda)(-\lambda)=0 $$

The eigenalue of this matrix is $\lambda=0$. 

Therefore $\begin{bmatrix} 0&0\\0&0 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  =  \begin{bmatrix} 0\\0\end{bmatrix} $. The eigenvectors of the matrix can be any vectors. 

The two standardized eigenvectors are thus $\vec v_{1} = (1, 0)$ and $\vec v_{2} = (0, 1)$. 


In [0]:
w1, v1 = LA.eig(np.matrix([[2,1],
                           [0,3]]))
print("\n 1. \n Eigenvalues ",w1, "\n Eigenvectors", v1)

w2, v2 = LA.eig(np.matrix([[0,0],
                           [0,0]]))
print("\n 2. \n Eigenvalues ",w2, "\n Eigenvectors", v2)


 1. 
 Eigenvalues  [2. 3.] 
 Eigenvectors [[1.         0.70710678]
 [0.         0.70710678]]

 2. 
 Eigenvalues  [0. 0.] 
 Eigenvectors [[1. 0.]
 [0. 1.]]


## 3. $\begin{bmatrix} 3&2\\6&-1 \end{bmatrix}$

$$ det \begin{vmatrix} 3-\lambda&2\\6&-1-\lambda \end{vmatrix} = (3-\lambda)(-1-\lambda) - 12 =0 \\
-3+ \lambda -3\lambda +\lambda^2-12 = 0\\
\lambda^2 - 2\lambda -15 = 0\\
(\lambda+3)(\lambda-5)=0
$$

The eigenalue of this matrix is $\lambda_{1}=-3$, $\lambda_{2}=5$. 

When $\lambda_{1}=-3$, 

$$\begin{bmatrix} 3-(-3)&2\\6&-1-(-3) \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} 6&2\\6&2 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix} =  \begin{bmatrix} 6v_{1} + 2 v_{2}\\6v_{1} + 2v_{2}  \end{bmatrix} = \begin{bmatrix} 0\\0\end{bmatrix} \\
v_{2} = - 3v_{1} \\
v_{1}^2 + v_{2}^2  = v_{1}^2 + (-3v_{1})^2 = 10v_{1}^2 = 1$$

Therefore, $v_{1} = \frac{\sqrt10}{10}$, $v_{2} = -\frac{3 \sqrt10}{10}$

When $\lambda_{2}=5$, 

$$\begin{bmatrix} 3-5&2\\6&-1-5 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} -2&2\\6&-6 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix} =  \begin{bmatrix} -2v_{1} + 2 v_{2}\\6v_{1}  -6v_{2} \end{bmatrix} = \begin{bmatrix} 0\\0\end{bmatrix} \\
 + = 0\\
v_{2} = v_{1} \\
v_{1}^2 + v_{2}^2  = 2v_{1}^2  = 1$$

Therefore, $v_{1} = \frac{\sqrt2}{2}$, $v_{2} = \frac{\sqrt2}{2}$

The two standardized eigenvectors are thus $\vec v_{1} = (\frac{\sqrt10}{10}, -\frac{3 \sqrt10}{10})$ and $\vec v_{2} = (\frac{\sqrt2}{2}, \frac{\sqrt2}{2})$. 

<br>

## 4. $\begin{bmatrix} 1&2\\3&2 \end{bmatrix}$

$$ det \begin{vmatrix} 1-\lambda&2\\3&2-\lambda \end{vmatrix} = (1-\lambda)(2-\lambda) - 6 =0 \\
2-2\lambda -\lambda +\lambda^2-6 = 0\\
\lambda^2 - 3\lambda -4 = 0\\
(\lambda+1)(\lambda-4)=0
$$

The eigenalue of this matrix is $\lambda_{1}=-1$, $\lambda_{2}=4$. 

When $\lambda_{1}=-1$, 

$$\begin{bmatrix} 1-(-1)&2\\3&2-(-1) \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} 2&2\\3&3 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix} =  \begin{bmatrix} 2v_{1} + 2 v_{2}\\3v_{1} + 3v_{2} \end{bmatrix} = \begin{bmatrix} 0\\0\end{bmatrix} \\
v_{2} = - v_{1} \\
v_{1}^2 + v_{2}^2  = 2v_{1}^2 = 1$$

Therefore, $v_{1} = \frac{\sqrt2}{2}$, $v_{2} = -\frac{\sqrt2}{2}$

When $\lambda_{1}=4$, 

$$\begin{bmatrix} 1-4&2\\3&2-4 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix}  = \begin{bmatrix} -3&2\\3&-2 \end{bmatrix} \cdot \begin{bmatrix} v_{1}\\v_{2} \end{bmatrix} \begin{bmatrix} -3v_{1} + 2 v_{2}\\3v_{1} -2 v_{2} \end{bmatrix} =  \begin{bmatrix} 0\\0\end{bmatrix} \\
v_{2} = - \frac{3}{2}v_{1} \\
v_{1}^2 + v_{2}^2  = v_{1}^2 + (\frac{2}{3}v_{1})^2 = \frac{13}{9}v_{1}^2 = 1$$

Therefore, $v_{1} = \frac{\sqrt10}{10}$, $v_{2} = -\frac{3 \sqrt10}{10}$

The two standardized eigenvectors are thus $\vec v_{1} = span(\frac{\sqrt2}{2}, -\frac{\sqrt2}{2})$ and $\vec v_{2} = span(\frac{\sqrt10}{10}, -\frac{3 \sqrt10}{10})$. 





In [0]:
w3, v3 = LA.eig(np.matrix([[3,2],
                           [6,-1]]))
print("\n 3. \n Eigenvalues ",w3, "\n Eigenvectors \n", v3)

w4, v4 = LA.eig(np.matrix([[1,2],
                           [3,2]]))
print("\n 4. \n Eigenvalues ",w4, "\n Eigenvectors \n", v4)


 3. 
 Eigenvalues  [ 5. -3.] 
 Eigenvectors 
 [[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]

 4. 
 Eigenvalues  [-1.  4.] 
 Eigenvectors 
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


## 5. $\begin{bmatrix} 2&1&0\\0&2&0\\2&3&1 \end{bmatrix}$

$$ det \begin{vmatrix} \begin{bmatrix} 2&1&0\\0&2&0\\2&3&1 \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 2-\lambda&1&0\\0&2-\lambda&0\\2&3&1-\lambda \end{vmatrix} = (2-\lambda)(2-\lambda)(1-\lambda) =0 \\
$$

The three eigenalue of this matrix is $\lambda_{1}=1$, $\lambda_{2}=\lambda_{3}=2$. 

When $\lambda_{1}=1$, 

$$\begin{bmatrix} 2-1&1&0\\0&2-1&0\\2&3&1-1 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v{3} \end{bmatrix} = \begin{bmatrix} v_{1} + v_{2}\\ v_{2}\\2v_{1}+3v_{2} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}= v_{2}=0\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$. 

Therefore, $v_{1}= v_{2}=0$, $v_{3}=1$. 

When $\lambda_{2}=\lambda_{3}=2$, 

$$\begin{bmatrix} 2-2&1&0\\0&2-2&0\\2&3&1-2 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v{3} \end{bmatrix} = \begin{bmatrix}  v_{2}\\ 0\\2v_{1}+3v_{2}- v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{2}=0\\
2v_{1}=v_{3}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$. 

Therefore, $v_{1}=\frac{1}{\sqrt5}, v_{2}=0$, $v_{3}=\frac{2}{\sqrt5}$. 

The three standardized eigenvectors are thus $\vec v_{1} = span \left( 0,0,1\right)$ and $\vec v_{2} = \vec v_{3} = span(\frac{1}{\sqrt5},0,\frac{2}{\sqrt5})$. 


In [0]:
w5, v5 = LA.eig(np.matrix([[2,1,0],
                         [0,2,0],
                         [2,3,1]]))
print("\n 5. \n Eigenvalues ",w5, "\n Eigenvectors \n", v5)


 5. 
 Eigenvalues  [1. 2. 2.] 
 Eigenvectors 
 [[ 0.00000000e+00  4.47213595e-01 -4.47213595e-01]
 [ 0.00000000e+00  0.00000000e+00  1.98602732e-16]
 [ 1.00000000e+00  8.94427191e-01 -8.94427191e-01]]


## 6. $\begin{bmatrix} 4&2&-2\\-5&3&2\\-2&4&1 \end{bmatrix}$

$$ det \begin{vmatrix} \begin{bmatrix} 4&2&-2\\-5&3&2\\-2&4&1 \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 4-\lambda&2&-2\\-5&3-\lambda&2\\-2&4&1-\lambda \end{vmatrix}\\ = (4-\lambda)(3-\lambda)(1-\lambda)-8+20-(-10)(1-\lambda)-8(4-\lambda)-4(3-\lambda) \\
=(\lambda-5)(\lambda-2)(\lambda-1)=0 \\
$$

The three eigenalue of this matrix is $\lambda_{1}=5$, $\lambda_{2}=2, \lambda_{3}=1$. 

When $\lambda_{1}=5$, 

$$\begin{bmatrix}4-5 &2&-2\\-5&3-5&2\\-2&4&1-5  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v{3} \end{bmatrix} = \begin{bmatrix} -v_{1} + 2v_{2}- 2v_{3}\\ -5v_{1}-2v_{2}+2v_{3}\\-2v_{1}+4v_{2}+3v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}= 2v_{2}-v_{3}=0\\
(-2)(2v_{2}-v_{3})+4v_{2}+3v_{3} = 5v_{3}=0\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$. 

Therefore, $v_{1}= v_{2}=\frac{1}{\sqrt2}$, $v_{3}=0$. 

When $\lambda_{2}=2$, 

$$\begin{bmatrix}4-2 &2&-2\\-5&3-2&2\\-2&4&1-2 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v{3} \end{bmatrix} = \begin{bmatrix}2v_{1} + 2v_{2}- 2v_{3}\\ -5v_{1}+v_{2}+2v_{3}\\-2v_{1}+4v_{2}-v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}=v_{2}\\
v_{3}= v_{1}+ v_{2}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=v_{2}=\frac{1}{\sqrt6}$, $v_{3}=\frac{2}{\sqrt6}$. 

When $\lambda_{2}=1$, 

$$\begin{bmatrix}4-1 &2&-2\\-5&3-1&2\\-2&4&1-1 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v{3} \end{bmatrix} = \begin{bmatrix}3v_{1} + 2v_{2}- 2v_{3}\\ -5v_{1}+2v_{2}+2v_{3}\\-2v_{1}+4v_{2} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}=2v_{2}\\
v_{3}= 4v_{2}=\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{2}{\sqrt21}, v_{2}=\frac{1}{\sqrt21}$, $v_{3}=\frac{4}{\sqrt21}$. 

The three standardized eigenvectors are thus $\vec v_{1} = span(\frac{1}{\sqrt2}, \frac{1}{\sqrt2},v_{3}=0)$, $\vec v_{2} = span(\frac{1}{\sqrt6}, \frac{1}{\sqrt6}, \frac{2}{\sqrt6})$, and $\vec v_{3} = span(\frac{2}{\sqrt21}, \frac{1}{\sqrt21}, \frac{4}{\sqrt21})$. 


In [0]:
w6, v6 = LA.eig(np.matrix([[4,2,1],
                           [-5,3,2],
                           [-1,4,1]]))
print("\n 6. \n Eigenvalues ",w6, "\n Eigenvectors \n", v6)


 6. 
 Eigenvalues  [ 4.5+3.27871926j  4.5-3.27871926j -1. +0.j        ] 
 Eigenvectors 
 [[-5.44347183e-03-0.53542848j -5.44347183e-03+0.53542848j
   5.02674854e-17+0.j        ]
 [ 6.42329676e-01+0.j          6.42329676e-01-0.j
  -4.47213595e-01+0.j        ]
 [ 4.68138577e-01-0.28556186j  4.68138577e-01+0.28556186j
   8.94427191e-01+0.j        ]]


## 7. $\begin{bmatrix} 1&2&3\\0&4&5\\0&0&6 \end{bmatrix}$


$$ det \begin{vmatrix} \begin{bmatrix} 1&2&3\\0&4&5\\0&0&6 \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 1-\lambda &2&3\\0&4-\lambda &5\\0&0&6-\lambda  \end{vmatrix}\\ = (1-\lambda)(4-\lambda)(6-\lambda)=0 \\
$$

The three eigenalue of this matrix is $\lambda_{1}=1$, $\lambda_{2}=4, \lambda_{3}=6$. 

When $\lambda_{1}=1$, 

$$\begin{bmatrix} 1-1&2&3\\0&4-1&5\\0&0&6-1  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} 2v_{2}+3v_{3}\\3v_{2}+5v_{3}\\5v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{2}=v_{3}=0\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=1, v_{2}=v_{3}=0$. 

When $\lambda_{2}=4$, 

$$\begin{bmatrix} 1-4&2&3\\0&4-4&5\\0&0&6-4  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -3v_{1}+ 2v_{2}+3v_{3}\\5v_{3}\\2v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
-3v_{1}+2v_{2}=0\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{2}{\sqrt13}, v_{2}=\frac{3}{\sqrt13}, v_{3}=0$. 

When $\lambda_{3}=6$, 

$$\begin{bmatrix} 1-6&2&3\\0&4-6&5\\0&0&6-6  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -5v_{1}+ 2v_{2}+3v_{3}\\-2v_{2}+5v_{3}\\0 \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{2}=\frac{5}{2}v_{3}\\
v_{1}=\frac{8}{5}v_{3}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{12}{25}\sqrt109, v_{2}=\frac{3}{4}\sqrt109, v_{3}=\frac{3}{10}\sqrt109$. 

The three eigenvectors for this matrix is $\vec v_{1}= span(1,0,0), \vec v_{2} = span(\frac{2}{\sqrt13},\frac{3}{\sqrt13}, 0),  \vec v_{3}=span(\frac{12}{25}\sqrt109, \frac{3}{4}\sqrt109, \frac{3}{10}\sqrt109)$



In [0]:
w7, v7 = LA.eig(np.matrix([[1,2,3],
                           [0,4,5],
                           [0,0,6]]))
print("\n 7. \n Eigenvalues ",w7, "\n Eigenvectors \n", v7)


 7. 
 Eigenvalues  [1. 4. 6.] 
 Eigenvectors 
 [[1.         0.5547002  0.51084069]
 [0.         0.83205029 0.79818857]
 [0.         0.         0.31927543]]


10.44030650891055

## 8. $\begin{bmatrix} 1&-1&-1\\1&3&1\\-3&1&-1 \end{bmatrix}$

$$ det \begin{vmatrix} \begin{bmatrix} 1&-1&-1\\1&3&1\\-3&1&-1 \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 1-\lambda&-1&-1\\1&3-\lambda&1\\-3&1&-1-\lambda  \end{vmatrix}\\ = \lambda^3-3\lambda^2+2\lambda-12=0 \\
$$

The three eigenalue of this matrix is $\lambda_{1}=2$, $\lambda_{2}=-2, \lambda_{3}=3$. 

When $\lambda_{1}=2$, 

$$\begin{bmatrix} 1-2&-1&-1\\1&3-2&1\\-3&1&-1-2  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -v_{1}-v_{2}-v_{3}\\v_{1}+v_{2}+v_{3}\\-3v_{1}+v_{2}-v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=0, v_{2}=-\frac{1}{\sqrt2}, v_{3}=\frac{1}{\sqrt2}$. 

When $\lambda_{2}=-2$, 

$$\begin{bmatrix} 1+2&-1&-1\\1&3+2&1\\-3&1&-1+2  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} 3v_{1}-v_{2}-v_{3}\\v_{1}+5v_{2}+v_{3}\\-3v_{1}+v_{2}+v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}=-v_{2}\\
v_{3}=-4v_{1}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{\sqrt2}{6}, v_{2}=-\frac{\sqrt2}{6}, v_{3}=\frac{2\sqrt2}{3}$. 

When $\lambda_{3}=3$, 

$$\begin{bmatrix} 1-3&-1&-1\\1&3-3&1\\-3&1&-1-3  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -2v_{1}-v_{2}-v_{3}\\v_{1}+v_{3}\\-3v_{1}+v_{2}-4v_{3}\end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}=-v_{3}\\
v_{2}=v_{1}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=-\frac{1}{\sqrt3}, v_{2}=-\frac{1}{\sqrt3}, v_{3}=-\frac{1}{\sqrt3}$. 

The three eigenvectors for this matrix is $\vec v_{1}= span(0, -\frac{1}{\sqrt2},\frac{1}{\sqrt2}), \vec v_{2} = span(\frac{\sqrt2}{6}, -\frac{\sqrt2}{6}, \frac{2\sqrt2}{3}),  \vec v_{3}=span(-\frac{1}{\sqrt3}, \frac{1}{\sqrt3}, \frac{1}{\sqrt3})$

In [0]:
w8, v8 = LA.eig(np.matrix([[1,-1,-1],
                           [1,3,1],
                           [-3,1,-1]]))
print("\n 8. \n Eigenvalues ",w8, "\n Eigenvectors \n", v8)


 8. 
 Eigenvalues  [-2.  2.  3.] 
 Eigenvectors 
 [[ 2.35702260e-01 -7.07106781e-01 -5.77350269e-01]
 [-2.35702260e-01  7.45148041e-16  5.77350269e-01]
 [ 9.42809042e-01  7.07106781e-01  5.77350269e-01]]


## 9. $\begin{bmatrix} 1&0&0&0\\2&-1&0&0\\5&3&2&0\\7&4&6&2 \end{bmatrix}$

In [0]:
w9, v9 = LA.eig(np.matrix([[1,0,0,0],
                           [2,-1,0,0],
                           [5,3,2,0],
                           [7,4,6,2]]))
print("\n 9. \n Eigenvalues ",w9, "\n Eigenvectors \n", v9)


 9. 
 Eigenvalues  [ 2.  2. -1.  1.] 
 Eigenvectors 
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.63981839e-02]
 [ 0.00000000e+00  0.00000000e+00  6.39602149e-01  2.63981839e-02]
 [ 0.00000000e+00  7.40148683e-17 -6.39602149e-01 -2.11185471e-01]
 [ 1.00000000e+00 -1.00000000e+00  4.26401433e-01  9.76732803e-01]]


# 9 Properties of Eigenvalues and Eigenvectors

---

Let $A$ be the following matrix: $$\begin{bmatrix} 1&1&-1\\2&3&-4\\4&1&-4 \end{bmatrix}$$

Use Maple to do the following:


## 1. Find the eigenvalues of $A$ and their associated eigenvectors

$$ det \begin{vmatrix} \begin{bmatrix} 1&1&-1\\2&3&-4\\4&1&-4 \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 1-\lambda&1&-1\\2&3-\lambda&-4\\4&1&-4-\lambda \end{vmatrix} \\
(1-\lambda)(3-\lambda)(-4-\lambda)-16-2-2(-4-\lambda)+4(1-\lambda)+4(3-\lambda)=0
$$


The three eigenalue of this matrix is $\lambda_{1}=2$, $\lambda_{2}=1, \lambda_{3}=-3$. 

When $\lambda_{1}=2$, 

$$\begin{bmatrix}1-2&1&-1\\2&3-2&-4\\4&1&-4-2 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -v_{1}+v_{2}-v_{3}\\2v_{1}+v_{2}-4v_{3}\\4v_{1}+v_{2}-6v_{3}\end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{1}{\sqrt6}, v_{2}=\frac{2}{\sqrt6}, v_{3}=\frac{1}{\sqrt6}$. 

When $\lambda_{2}=1$, 

$$\begin{bmatrix} 1-1&1&-1\\2&3-1&-4\\4&1&-4-1  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} v_{2}-v_{3}\\2v_{1}+2v_{2}-4v_{3}\\4v_{1}+v_{2}-5v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=v_{2}=v_{3}=\frac{1}{\sqrt3}$. 

When $\lambda_{3}=-3$, 

$$\begin{bmatrix} 1+3&1&-1\\2&3+3&-4\\4&1&-4+3  \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} 4v_{1} + v_{2}-v_{3}\\2v_{1}+6v_{2}-4v_{3}\\4v_{1}+v_{2}-v_{3}\end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}=-v_{3}\\
v_{2}=v_{1}\\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{\sqrt19}{57}, v_{2}=\frac{7\sqrt19}{57}, v_{3}=\frac{11\sqrt19}{57}$. 

The three eigenvectors for this matrix is $\vec v_{1}= span(\frac{1}{\sqrt6},\frac{2}{\sqrt6},\frac{1}{\sqrt6}), \vec v_{2} = span(\frac{1}{\sqrt3}, \frac{1}{\sqrt3}, \frac{1}{\sqrt3}),  \vec v_{3}=span(\frac{\sqrt19}{57}, \frac{7\sqrt19}{57}, \frac{11\sqrt19}{57})$

<br>

## 2. Standardize the eigenvectors.

The standardized eigenvectors are $\vec v_{1}=\begin {bmatrix} \frac{1}{\sqrt6}\\\frac{2}{\sqrt6}\\\frac{1}{\sqrt6}\end{bmatrix}$, $\vec v_{2} = \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\ \frac{1}{\sqrt3}\end{bmatrix}$, $\vec v_{3}=\begin {bmatrix} \frac{\sqrt19}{57}
\\ \frac{7\sqrt19}{57}\\\frac{11\sqrt19}{57}\end{bmatrix}$





In [0]:
w, v = LA.eig(np.matrix([[1,1,-1],
                         [2,3,-4],
                         [4,1,-4]]))
print("eigenvalue: \n", w, "\n eigenvector: \n", v.round(decimals=4))

eigenvalue: 
 [-3.  1.  2.] 
 eigenvector: 
 [[ 0.0765  0.5774 -0.4082]
 [ 0.5353  0.5774 -0.8165]
 [ 0.8412  0.5774 -0.4082]]


## 3. Show that the eigenvectors are orthogonal to each other.
 
Eigenvectors are not orthogonal to each other for matrix $A$ because $A$ is not symmetric.



In [0]:
np.matrix([0.076,0.577,-0.408]).T * np.matrix([0.076,0.577,-0.408])

matrix([[ 0.005776,  0.043852, -0.031008],
        [ 0.043852,  0.332929, -0.235416],
        [-0.031008, -0.235416,  0.166464]])

## 4. Find the trace of $A$. Verify that it is equal to the sum of the eigenvalues.

$$tr(A) = \sum_{n=1}^{n}A_{n*n} = a_{11} + a_{22} + \cdots + a_{nn} = 1+3+(-4) = 0$$

$$\sum (eig) = 2+1+(-3)=0$$

<br>

## 5. Find the determinant of $A$. Verify that it is equal to the product of the eigenvalues.

$$det|A| = det \begin{vmatrix} 1&1&-1\\2&3&-4\\4&1&-4 \end{vmatrix} = -12-16-2+8+4+12=-6$$

$$\prod(eig) = 2*1*(-3)=-6 $$

<br>

## 6. Find the rank of $A$. Verify that it is equal to the number of non-zero eigenvalues.

$$\begin{bmatrix} 1&1&-1\\2&3&-4\\4&1&-4 \end{bmatrix} 
\xrightarrow[R_{3}+(-4)R_{1} \rightarrow R_{3}]{R_{2}+(-2)R_{1} \rightarrow R_{2}} 
\begin{bmatrix} 1&1&-1\\0&1&-2\\0&-3&0 \end{bmatrix} 
\xrightarrow[]{R_{3}+3R_{2} \rightarrow R_{3}} 
\begin{bmatrix} 1&1&-1\\0&1&-2\\0&0&-6 \end{bmatrix}
\xrightarrow[]{-\frac{1}{6}R_{3}} 
\begin{bmatrix} 1&1&-1\\0&1&-2\\0&0&1 \end{bmatrix}
$$

Therefore, $rank(A) = 3$, and matrix $A$ hs 3 non-zero eigenvalues. 







## 7. Find the eigenvalues of $A^2$ and their associated eigenvectors. How do they compare with the eigenvalues and eigenvectors of $A$?

$$A^2 = A\prime \times A = \begin{bmatrix} 1&2&4\\1&3&1\\-1&-4&-4 \end{bmatrix} \times \begin{bmatrix} 1&1&-1\\2&3&-4\\4&1&-4 \end{bmatrix} =\begin{bmatrix} -1&3&-1\\-8&7&2\\-10&3&8 \end{bmatrix}  $$

The eigenvalues of matrix $A^2$ is $\lambda_{1} = 9, \lambda_{2} = 1,\lambda_{3} = 3 $. They are also the square of the eigenvalues of the original matrix $A$.

The eigenvectors of matrix $A^2$ and $A$ are identical, both are $\vec v_{1}=\begin {bmatrix} \frac{1}{\sqrt6}\\\frac{2}{\sqrt6}\\\frac{1}{\sqrt6}\end{bmatrix}$, $\vec v_{2} = \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\ \frac{1}{\sqrt3}\end{bmatrix}$, $\vec v_{3}=\begin {bmatrix} \frac{\sqrt19}{57}
\\ \frac{7\sqrt19}{57}\\\frac{11\sqrt19}{57}\end{bmatrix}$

<br>

## 8. Find the eigenvalues of $A^{-1}$ and their associated eigenvectors. How do they compare with the eigenvalues and eigenvectors of $A$?

$$adj(A) = \begin{bmatrix} -8&-8&-10\\-(-3)&0&-(-3)\\-1&-(-2)&1 \end{bmatrix} \prime = \begin{bmatrix} -8&3&-1\\-8&0&2\\-10&3&1 \end{bmatrix} $$

$$det(A)=-6$$

$$A^{-1} = \frac{1}{det(A)} adj(A) = \begin{bmatrix} \frac{4}{3}&-\frac{1}{2}&\frac{1}{6}\\\frac{4}{3}&0&-\frac{1}{3}\\\frac{5}{3}&-\frac{1}{2}&-\frac{1}{6} \end{bmatrix}$$

The eigenvalues of $A^{-1}$ are $\lambda_{1} = -\frac{1}{3}, \lambda_{2} = 1, \lambda_{3} = \frac{1}{2}$. They are the inverse of the eigenvalues of original matrix $A$.

The eigenvectors of matrix $A^{-1}$ and $A$ are also identical $\vec v_{1}=\begin {bmatrix} \frac{1}{\sqrt6}\\\frac{2}{\sqrt6}\\\frac{1}{\sqrt6}\end{bmatrix}$, $\vec v_{2} = \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\ \frac{1}{\sqrt3}\end{bmatrix}$, $\vec v_{3}=\begin {bmatrix} \frac{\sqrt19}{57}
\\ \frac{7\sqrt19}{57}\\\frac{11\sqrt19}{57}\end{bmatrix}$


In [0]:
print("A^2: \n", LA.matrix_power(np.matrix([[1,1,-1],[2,3,-4],[4,1,-4]]), n=2))
print("\n A.inv: \n", LA.inv(np.matrix([[1,1,-1],[2,3,-4],[4,1,-4]])))
print("\n eig(A^2): \n", LA.eig(LA.matrix_power(np.matrix([[1,1,-1],[2,3,-4],[4,1,-4]]), n=2)))
print("\n eig(A.inv): \n", LA.eig(LA.inv(np.matrix([[1,1,-1],[2,3,-4],[4,1,-4]]))))
print("\n eig(A): \n", LA.eig(np.matrix([[1,1,-1],[2,3,-4],[4,1,-4]])))

A^2: 
 [[ -1   3  -1]
 [ -8   7   2]
 [-10   3   8]]

 A.inv: 
 [[ 1.33333333 -0.5         0.16666667]
 [ 1.33333333  0.         -0.33333333]
 [ 1.66666667 -0.5        -0.16666667]]

 eig(A^2): 
 (array([9., 1., 4.]), matrix([[ 0.07647191,  0.57735027, -0.40824829],
        [ 0.53530338,  0.57735027, -0.81649658],
        [ 0.84119102,  0.57735027, -0.40824829]]))

 eig(A.inv): 
 (array([-0.33333333,  1.        ,  0.5       ]), matrix([[-0.07647191, -0.57735027, -0.40824829],
        [-0.53530338, -0.57735027, -0.81649658],
        [-0.84119102, -0.57735027, -0.40824829]]))

 eig(A): 
 (array([-3.,  1.,  2.]), matrix([[ 0.07647191,  0.57735027, -0.40824829],
        [ 0.53530338,  0.57735027, -0.81649658],
        [ 0.84119102,  0.57735027, -0.40824829]]))


# 10 More Properties of Eigenvalues and Eigenvectors

---


Let $A$ be the following matrix $A= \begin{bmatrix} 2&4&2\\4&0&4\\2&4&2 \end{bmatrix}$. 

Use Maple to do the following:

## 1. Find the eigenvalues of $A$ and their associated eigenvectors.

## 2. Standardize the eigenvectors.

$$ det \begin{vmatrix} \begin{bmatrix} 2&4&2\\4&0&4\\2&4&2  \end{bmatrix} - \begin{bmatrix} \lambda&0&0\\0&\lambda&0\\0&0&\lambda \end{bmatrix} \end{vmatrix} = det \begin{vmatrix} 2-\lambda&4&2\\4&0-\lambda&4\\2&4&2-\lambda  \end{vmatrix} \\
(2-\lambda)(-\lambda)(2-\lambda)-32-32-16(2-\lambda)-16(2-\lambda)-4(-\lambda)=0
$$


The three eigenalue of this matrix is $\lambda_{1}=8$, $\lambda_{2}=0, \lambda_{3}=-4$. 

When $\lambda_{1}=8$, 

$$\begin{bmatrix}2-8&4&2\\4&0-8&4\\2&4&2-8 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} -6v_{1}+4v_{2}+2v_{3}\\4v_{1}-8v_{2}+4v_{3}\\2v_{1}+4v_{2}-6v_{3}\end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=v_{2}=v_{3}=\frac{1}{\sqrt3}$. 

When $\lambda_{2}=0$, 

$$\begin{bmatrix} 2-0&4&2\\4&0-0&4\\2&4&2-0   \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} 2v_{1}+ 4v_{2}+2v_{3}\\4v_{1}+4v_{3}\\2v_{1}4v_{2}+2v_{3} \end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{1}{\sqrt2}, v_{2}=0, v_{3}=-\frac{1}{\sqrt2}$. 

When $\lambda_{3}=-4$, 

$$\begin{bmatrix} 2+4&4&2\\4&0+4&4\\2&4&2+4 \end{bmatrix} \cdot \begin{bmatrix}v_{1}\\v_{2}\\v_{3} \end{bmatrix} = \begin{bmatrix} 6v_{1} +4v_{2}+2v_{3}\\4v_{1}+4v_{2}+4v_{3}\\2v_{1}+6v_{2}-4v_{3}\end{bmatrix} = \begin{bmatrix} 0\\ 0\\0 \end{bmatrix} \\
v_{1}^2 + v_{2}^2 +v_{3}^2 =1$$ 

Therefore, $v_{1}=\frac{1}{\sqrt6}, v_{2}=-\frac{2}{\sqrt6}, v_{3}=\frac{1}{\sqrt6}$. 

The three standardized eigenvectors are $\vec v_{1}=\begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\end{bmatrix}$, $\vec v_{2} = \begin {bmatrix}\frac{1}{\sqrt2}\\0\\-\frac{1}{\sqrt2} \end{bmatrix}$, $\vec v_{3}=\begin {bmatrix} \frac{1}{\sqrt6}\\-\frac{2}{\sqrt6}\\\frac{1}{\sqrt6}\end{bmatrix}$


In [0]:
LA.eig(np.matrix([[2,4,2],
                  [4,0,4],
                  [2,4,2]]))

(array([ 8.00000000e+00, -3.51535614e-17, -4.00000000e+00]),
 matrix([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
         [-5.77350269e-01, -6.78782813e-17, -8.16496581e-01],
         [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

## 3. Show that the eigenvectors are orthogonal to each other.

$$\vec v_{1} \times \vec v_{2} = \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\end{bmatrix} \times \begin {bmatrix}\frac{1}{\sqrt2}\\0\\-\frac{1}{\sqrt2} \end{bmatrix} = \frac{1}{\sqrt3}*\frac{1}{\sqrt2} +0 -\frac{1}{\sqrt3}*\frac{1}{\sqrt2} =  0$$

$$\vec v_{1} \times \vec v_{3} = \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt6}\\-\frac{2}{\sqrt6}\\\frac{1}{\sqrt6} \end{bmatrix} = \frac{1}{\sqrt3} * \frac{1}{\sqrt6} - \frac{1}{\sqrt3} * \frac{2}{\sqrt6} + \frac{1}{\sqrt3} * \frac{1}{\sqrt6} = 0$$

$$\vec v_{2} \times \vec v_{3} = \begin {bmatrix} \frac{1}{\sqrt2}\\0\\-\frac{1}{\sqrt2}\end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt6}\\-\frac{2}{\sqrt6}\\\frac{1}{\sqrt6} \end{bmatrix} = \frac{1}{\sqrt2} * \frac{1}{\sqrt6} -0 + \frac{1}{\sqrt2} * \frac{1}{\sqrt6} = 0$$

The eigenvectors are orthogonal to each other is thus proven.

<br>

## 4. Show that for each eigenvector $x_{i}, x_{i}\prime x_{i} = 1$.

$$\vec v_{1} \prime \times \vec v_{1} = \begin {bmatrix} \frac{1}{\sqrt3}&\frac{1}{\sqrt3}&\frac{1}{\sqrt3}\end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\\\frac{1}{\sqrt3}\end{bmatrix} = \frac{1}{\sqrt3} * \frac{1}{\sqrt3} *3 = 1$$

$$\vec v_{2} \prime \times \vec v_{2} = \begin {bmatrix} \frac{1}{\sqrt2}&0&-\frac{1}{\sqrt2} \end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt2}\\0\\-\frac{1}{\sqrt2} \end{bmatrix} = \frac{1}{\sqrt2} * \frac{1}{\sqrt2} *2 = 1$$

$$\vec v_{3} \prime \times \vec v_{3} = \begin {bmatrix}  \frac{1}{\sqrt6}&-\frac{2}{\sqrt6}&\frac{1}{\sqrt6} \end{bmatrix} \times \begin {bmatrix}  \frac{1}{\sqrt6}\\-\frac{2}{\sqrt6}\\\frac{1}{\sqrt6} \end{bmatrix} = \frac{1}{\sqrt6} * \frac{1}{\sqrt6} *2 + \frac{2}{\sqrt6} * \frac{2}{\sqrt6} = 1$$


## 5. Let $X = \begin{bmatrix} x_{1} & x_{2} & x_{3}\end{bmatrix}$, where the $x_{i}$ are the eigenvectors. Verify that $X^{-1} = X\prime$.

$$X = \begin {bmatrix} \frac{1}{\sqrt3}& \frac{1}{\sqrt2}&\frac{1}{\sqrt6} \\ \frac{1}{\sqrt3}&0&-\frac{2}{\sqrt6} \\ \frac{1}{\sqrt3}&-\frac{1}{\sqrt2}&\frac{1}{\sqrt6} \end{bmatrix} $$

$$X\prime = \begin {bmatrix} \frac{1}{\sqrt3}&\frac{1}{\sqrt3}&\frac{1}{\sqrt3} \\  \frac{1}{\sqrt2}&0&-\frac{1}{\sqrt2}  \\  \frac{1}{\sqrt6}&-\frac{2}{\sqrt6}&\frac{1}{\sqrt6}\end{bmatrix}$$

$$det|X| = 0$$, therefore $X$ is not invertible.

<br>

## 6. Find $Λ=X\prime AX$, and verify that it is a diagonal matrix.

$$\begin{aligned}
Λ &=  \begin {bmatrix} \frac{1}{\sqrt3}&\frac{1}{\sqrt3}&\frac{1}{\sqrt3} \\  \frac{1}{\sqrt2}&0&-\frac{1}{\sqrt2}  \\  \frac{1}{\sqrt6}&-\frac{2}{\sqrt6}&\frac{1}{\sqrt6}\end{bmatrix} \times \begin{bmatrix} 2&4&2\\4&0&4\\2&4&2 \end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt3}& \frac{1}{\sqrt2}&\frac{1}{\sqrt6} \\ \frac{1}{\sqrt3}&0&-\frac{2}{\sqrt6} \\ \frac{1}{\sqrt3}&-\frac{1}{\sqrt2}&\frac{1}{\sqrt6} \end{bmatrix} \\
&=\begin {bmatrix} \frac{8}{\sqrt3}&\frac{8}{\sqrt3}&\frac{8}{\sqrt3}\\ 0&0&0 \\ \frac{-4}{\sqrt6}&\frac{8}{\sqrt6}&\frac{-4}{\sqrt6} \\ \end{bmatrix} \times \begin {bmatrix} \frac{1}{\sqrt3}& \frac{1}{\sqrt2}&\frac{1}{\sqrt6} \\ \frac{1}{\sqrt3}&0&-\frac{2}{\sqrt6} \\ \frac{1}{\sqrt3}&-\frac{1}{\sqrt2}&\frac{1}{\sqrt6} \end{bmatrix}  \\
&= \begin {bmatrix} 8&0&0\\0&0&0\\0&0&4\\ \end {bmatrix}
\end{aligned}$$

Therefore $Λ$ is a diagnal matrix.




In [0]:
X = np.matrix([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
               [-5.77350269e-01, -6.78782813e-17, -8.16496581e-01],
               [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]])
np.round(X.T * np.matrix([[2,4,2],
                  [4,0,4],
                  [2,4,2]]) * X, decimals=3)

array([[ 8.,  0.,  0.],
       [ 0.,  0., -0.],
       [ 0., -0., -4.]])

## 7. Find the trace of $A$. Verify that it is equal to the sum of the eigenvalues.
$$A = \begin{bmatrix} 2&4&2\\4&0&4\\2&4&2 \end{bmatrix}$$
$$tr(A) = 2+0+2 =4$$
$$\sum_{\lambda_{i}}^{3}=8+0+(-4)=4$$

<br>

## 8. Find the determinant of $A$. Verify that it is equal to the product of the eigenvalues.

$$det(A) = 2*0*2+4*4*2+2*4*4-2*4*4-2*4*4-2*0*2 = 0 $$
$$\prod_{\lambda_{i}}^{3}=8*0*(-4)=0$$

<br>

## 9. Find the rank of $A$. Verify that it is equal to the number of non-zero eigenvalues.

$A$ has 2 non-zero eigenvectors $\lambda_{1}=8, \lambda_{3}=-4$

$$\begin{bmatrix} 2&4&2\\4&0&4\\2&4&2 \end{bmatrix}
\xrightarrow[\frac{1}{2}R_{1}]{R_{2}-2R_{1}, R_{3}-R_{1}}
\begin{bmatrix} 1&2&1\\0&-8&0\\0&0&0 \end{bmatrix}
\xrightarrow[]{-\frac{1}{8}R_{2}}
\begin{bmatrix} 1&2&1\\0&1&0\\0&0&0 \end{bmatrix}
$$

Therefore, $rank(A)=2$. 

<br>

## 10. Find the eigenvalues of $A^2$ and their associated eigenvectors. How do they compare with the eigenvalues and eigenvectors of $A$?

$$A^2=\begin{bmatrix} 24&16&24\\16&32&16\\24&16&24 \end{bmatrix}$$

The eigenvalues of $A^2$ is $\lambda_{1}=64$, $\lambda_{2}=0$, and $\lambda_{3}=16$. They are the square of the eigenvalues of $A$. 

The eigenvectors of $A^2$ are identical to those of $A$.

<br>

## 11. Find the eigenvalues of $A^{-1}$ and their associated eigenvectors. How do they compare with the eigenvalues and eigenvectors of A?

Since $det(A)=0$, the matrix is not inversable
<br>

## 12. Is $A$ idempotent?

The matrix $A$ is idempotent if and only if $A^{2}=A$. Therefore, matrix $A$ is NOT idempotent.

In [0]:
print("A^2: \n", LA.matrix_power(np.matrix([[2,4,2],[4,0,4],[2,4,2]]), n=2))
print("\n")
print("eig(A^2): \n", LA.eig(LA.matrix_power(np.matrix([[2,4,2],[4,0,4],[2,4,2]]), n=2)))

A^2: 
 [[24 16 24]
 [16 32 16]
 [24 16 24]]


eig(A^2): 
 (array([ 6.40000000e+01, -6.54261801e-16,  1.60000000e+01]), matrix([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.95271580e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))


# 11 Introduction Quadractic Forms

---



## 1. Define the types of quadratic forms. 

A quadratic form $Q(x) = X^T \cdot A \cdot X$ (equivalently a symmetric matrix $A$) is

- a. Positive definite if $Q(x) > 0, \forall x \neq 0 ∈ R$;
- b. Negative definite if $Q(x) \geq 0, \forall x \neq 0 ∈ R$;
- c. Positive semi-definite if $Q(x) < 0, \forall x \neq 0 ∈ R$
- d. Negative semi-definite if $Q(x) \leq 0, \forall x \neq 0 ∈ R$
- e. Indefinite if $Q(x) > 0$ for some $x$ and  $Q(x) < 0$ for some other $x$.

## 2. There are several ways to find if a matrix is positive definite. What are they?

A matrix is to be positive defitinte if
- 1) all its eigenvalues are positive 
- 2) all determinants of its principal sub-matrices are positive

## 3. Indicate the type of definiteness of the following matrices.

### a. $\begin{bmatrix}9&-3\\-3&1 \end{bmatrix}$

$$det \begin{vmatrix} 9-\lambda&-3\\-3&1-\lambda \end{vmatrix} = (9-\lambda)(1-\lambda)-9=0\\
\lambda_{1}=10, \lambda_{2}=0$$

Therefore, the matrix is positive semi-definite.

### b. $\begin{bmatrix}-4&2&-1\\2&-4&2\\-1&2&-4 \end{bmatrix}$

$$det \begin{vmatrix} -4-\lambda&2&-1\\2&-4-\lambda&2\\-1&2&-4-\lambda \end{vmatrix} = -(4+\lambda)^3+4-4+4(4+\lambda)+4(4+\lambda)+(4+\lambda)=0\\
-(4+\lambda)^3+9(4+\lambda)=0\\
\lambda_{1}=-1.628, \lambda_{2}=-3, \lambda_{3}=-7.372$$

Therefore, the matrix is negative definite.

### c. $\begin{bmatrix}2&-1.5\\-1.5&3 \end{bmatrix}$


$$det \begin{vmatrix} 2-\lambda&-1.5\\-1.5&3-\lambda \end{vmatrix} = (2-\lambda)(3-\lambda)-2.25=0\\
\lambda_{1}=4.18, \lambda_{2}=0.99$$

Therefore, the matrix is positive definite.

### d. $\begin{bmatrix}4&2&-2\\2&4&2\\-2&2&4 \end{bmatrix}$

$$det \begin{vmatrix} 4-\lambda&2&2\\2&4-\lambda&2\\-2&2&4-\lambda \end{vmatrix} = (4-\lambda)^3-8+8-4(4-\lambda)-4(4-\lambda)+4(4-\lambda)=0\\
(4-\lambda)^3-4(4-\lambda)=0\\
\lambda_{1}=6, \lambda_{2}=0$$

Therefore, the matrix is positive semi-definite.


In [0]:
print("lambda(a): \n", LA.eigvals(np.matrix([[9,-3],[-3,1]])))
print("lambda(b): \n", LA.eigvals(np.matrix([[-4,2,-1],[2,-4,2],[-1,2,-4]])))
print("lambda(c): \n", LA.eigvals(np.matrix([[2, -1.5],[-1.5,3]])))
print("lambda(d): \n", LA.eigvals(np.matrix([[4,2,-2],[2,4,2],[-2,2,4]])))

lambda(a): 
 [10.  0.]
lambda(b): 
 [-7.37228132 -3.         -1.62771868]
lambda(c): 
 [0.91886117 4.08113883]
lambda(d): 
 [ 6.0000000e+00 -4.4408921e-16  6.0000000e+00]
