In [0]:
import numpy as np
from numpy import linalg as LA

# Matrix Addition and Scalar Multiplication


---




For problems 1-3, find the indicated sums, if possible. 

1. $
\begin{bmatrix}1 & 3 \\5& 0\end{bmatrix}
+ 
\begin{bmatrix}-2 & 0 \\1 & 1\end{bmatrix}
=
\begin{bmatrix}1-2 & 3 +0\\5+1 & 0+1\end{bmatrix}
=
\begin{bmatrix}-1 & 3\\6 & 1\end{bmatrix}
$

<br>

2. 
$\begin{bmatrix}2 & 3\\15 & 7\end{bmatrix}
+
\begin{bmatrix} 1 & 0 & 6 \end{bmatrix}
$

This is not conformable. 

<br>

3. 
$
\begin{bmatrix}
2 & 0 & 2\\1 & 3 & 1\\1 & -1 & 4\end{bmatrix}
+
\begin{bmatrix}10&3&4\\1&0&1\\3&0&3\end{bmatrix}
=
\begin{bmatrix}3&3&6\\2&3&2\\4&-1&7\end{bmatrix}
$

<br>

4. Find the matrix A that satisfies the equation $A - 
\begin{bmatrix}0&-1\\0&0\end{bmatrix}
=
\begin{bmatrix}3&-1\\2&1\end{bmatrix}
$.

<br>

$$A = \begin{bmatrix} 3+0 & -1+(-1)\\ 2+0 & 1+0 \end{bmatrix}
=
\begin{bmatrix} 3 & -2\\ 2&1 \end{bmatrix}
$$

<br>

5. Let $ A =  \begin{bmatrix} b & c \\ 2b & 3c^2 \end{bmatrix}$ and $\alpha = 3$, find $\alpha A$.

<br>

$$ \alpha A = \begin{bmatrix} 3b & 3c \\ 6b & 9c^2 
\end{bmatrix} $$

<br>

6. Let $
A = \begin{bmatrix} 1&-2\\ 3b&5 \end{bmatrix}$ and $\alpha = 0.5$, find $\alpha A$.

<br>

$$\alpha A = \begin{bmatrix} 0.5 & -1\\ 1.5 & 2.5 \end{bmatrix}
$$

<br>

7. Let $\alpha - -2$, 
$ A = \begin{bmatrix}3 & -2\\1 & 5\end{bmatrix}$, and $B = \begin{bmatrix} 0 & -1\\ -3 & 5\end{bmatrix} $, find $\alpha (A+B)$ and $\alpha A + \alpha B$

<br>

$$ \alpha (A+B) = (-2) * \begin{bmatrix} 3+0 & -2+1\\1-3 & 5+4 \end{bmatrix}
= (-2) * \begin{bmatrix} 3 & -1\\-1 & 9 \end{bmatrix}
= \begin{bmatrix} -6 & 2\\ 2 & -18 \end{bmatrix}
$$

<br>

$$
\alpha A + \alpha B = (-2) * \begin{bmatrix} 3 & -2\\1 & 5 \end{bmatrix} + (-2) * \begin{bmatrix} 0 & 1\\-3 & 4\end{bmatrix}
=  \begin{bmatrix} -6 & 4\\ -2 & -10 \end{bmatrix} + \begin{bmatrix} 0 & -2\\ 6 & -8\end{bmatrix} = 
\begin{bmatrix} -6 & 2\\-8 & -18 \end{bmatrix}
$$

# Matrix Multiplication

---

1. Expand the equation $c_{ij} = \sum_{k=1}^{n}a_{ik}b_{kj}$ for $i = 1, 2; j = 1, 2, 3;$ and $n = 2$. 

$$c_{11} = a_{11}b_{11} + a_{12}b_{21} $$
$$c_{12} = a_{11}b_{12} + a_{12}b_{22} $$
$$c_{13} = a_{11}b_{13} + a_{12}b_{23} $$
$$c_{21} = a_{21}b_{11} + a_{22}b_{21} $$
$$c_{22} = a_{21}b_{12} + a_{22}b_{22} $$
$$c_{23} = a_{21}b_{13} + a_{22}b_{23} $$



2. Given $u\prime = [5 \ 1 \ 3], v\prime = [3 \ 1 \ -1], w\prime = [7 \ 5 \ 8]$, and $x\prime = [x_{1} \ x_{2} \ x_{3}]$, write our the column vectors $u, v, w, x$ and find the following products.

<center>

The column vectors are $u = \begin{bmatrix} 5 \\ 1\\3 \end{bmatrix}$, $v = \begin{bmatrix} 3 \\ 1\\ -1 \end{bmatrix}$, $w = \begin{bmatrix} 7 \\ 5 \\ 8 \end{bmatrix}$, $x = \begin{bmatrix} x_{1} \\ x_{2} \\ x_{3} \end{bmatrix} $.

<br>

a. $u_{(3*1)} v\prime_{(1*3)} = \begin{bmatrix} 15&3&9 \\ 5&1&3\\-5&-3&-3 \end{bmatrix} $

<br>

b. $x_{(3*1)} x\prime_{(1*3)} = \begin{bmatrix} x_{1}x_{1}&x_{2}x_{1}&x_{3}x_{1} \\ x_{1}x_{2}&x_{2}x_{2}& x_{3}x_{2} \\ x_{1}x_{3} & x_{2}x_{3} & x_{3}x_{3} \end{bmatrix} $

<br>

c. $u\prime_{(1*3)} v_{(3*1)} = 15 + 1-3 = 13$

<br>

d. $u\prime_{(1*3)} u_{(3*1)} = 25 + 1 + 9 = 35$



3. Find the following products, if possible.

<br>

a. $\begin{bmatrix} 1&2&-1\end{bmatrix} \times \begin{bmatrix} 1&3\end{bmatrix}$ is not conformable.

<br>

b. $\begin{bmatrix} 3&2&1\\ 0&1&-1 \end{bmatrix} \times \begin{bmatrix} -1&0 \\ 1&-3 \\ 2&4 \end{bmatrix} = \begin{bmatrix} -3+2+1 & 0-6+4 \\ 0-1+1 & 0-3-4 \end{bmatrix} = \begin{bmatrix} 0 & -2 \\ 0 & -78 \end{bmatrix}$

<br>

c. $\begin{bmatrix} 1&-1&2\\ 0&2&1\\1&0&3 \end{bmatrix} \times \begin{bmatrix} -2&0&-1\\ 0&1&1\\-1&2&1\end{bmatrix} = \begin{bmatrix} -2+0-2 & 0-1+4 & -1-1+2 \\ 0+0-1&0+2+2&0-2+1 \\ -2+0-3&0+0+6&-1+0+3 \end{bmatrix} =  \begin{bmatrix} -4 & 3 & 0 \\ -1 & 4 &-1 \\ -5 & 6 & 2 \end{bmatrix} $

<br>

d. $\begin{bmatrix} 1&4&7\\ 2&5&8\\3&6&9 \end{bmatrix} \times \begin{bmatrix} 1&0&0\\ 0&1&0\\0&0&1\end{bmatrix} = \begin{bmatrix}  1&4&7\\ 2&5&8\\3&6&9  \end{bmatrix} I =  \begin{bmatrix}  1&4&7\\ 2&5&8\\3&6&9  \end{bmatrix} $


4. Let $A = \begin{bmatrix} 1&0&2\\ 3&1&0 \end{bmatrix}$ and $B = \begin{bmatrix} -1&-3\\ 0&-1\\-2&0 \end{bmatrix}$. 

a. Find $AB$ and $BA$. Are they the same?

$$ A_{2\times 3}B_{3\times 2} = \begin{bmatrix} -1-4&-3\\ -3&-9-1 \end{bmatrix} =  \begin{bmatrix} -5&-3 \\ -3&-10 \end{bmatrix} $$

$$ B_{3\times 2}A_{2\times 3} = \begin{bmatrix} -1-9&-3&-2 \\ -3&-1&0 \\ -2&0&-4 \end{bmatrix} =  \begin{bmatrix} -10&-3&-2 \\ -3&-1&0 \\ -2&0&-4 \end{bmatrix} $$

$AB$ and $BA$ are not the same.

<br>

b. What is the trace of $AB$? What is the trace of $BA$? Are they the same?

The trace of an $n \times n $ matrix $A$ is defined as $Tr(a) = \sum_{i=1}^{n}a_{ii}$. It is the sum of all the diagonal elements

$$Tr(AB) = -5 - 10 = -15$$
$$Tr(BA) = -10 - 1 - 4 = -15 $$

They are not the same either. 

5. Let $ A = \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix}$, $ B = \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}$, and $ C = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix}$. Find $(A+B)C$ and $AC+BC$. Find $C(A +B)$ and $CA + CB$. What properties of matrix multiplication do the results support?

$$(A+B)C = (\begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}) \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -2&0&-2\\-2&0&-2 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -4&0\\-4&0 \end{bmatrix} $$
<br>
$$AC+BC = \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix} \times \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} = \begin{bmatrix} -8&8\\-23&20 \end{bmatrix} + \begin{bmatrix} 12&-8\\27&-20 \end{bmatrix} = \begin{bmatrix} 4&0\\4&0 \end{bmatrix} $$
<br>
$$C(A+B) = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times (\begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix})  = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \begin{bmatrix} -2&0&-2\\-2&0&-2 \end{bmatrix} = \begin{bmatrix} -4&0&-4\\-2&0&-2 \\ 0&0&0\end{bmatrix} $$
<br>
$$CA+CB = \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times \begin{bmatrix} -1&2&-3\\-4&5&-6 \end{bmatrix} +  \begin{bmatrix} 2&0\\-3&4\\0&0 \end{bmatrix} \times \begin{bmatrix} 3&-2&1\\6&-5&4 \end{bmatrix}  = \begin{bmatrix} -2&4&-6\\-12&14&-15 \\ 0&0&0 \end{bmatrix} + \begin{bmatrix} 6&-4&2\\15&-14&13\\0&0&0 \end{bmatrix} = \begin{bmatrix} 4&0&-4\\3&0&-2\\0&0&0 \end{bmatrix} $$
<br>
This operation shows that the commutative property of multiplication that holds in algebra does not holds for matrix. 

6. Let $I$ be a 3 by 3 identity matrix. Find $I^2$, $I^3$, and $I^4$. What is another name for this kind of matrix?. 

$$I = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^2 = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^3 = I^2 \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$
<br>
$$I^4 = I^3 \times \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix} = \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1 \end{bmatrix}$$

They are all identity matrices.

# Determinants


---

Use the expansion-by-cofactor method (_Green and Carroll, 60-63_) to find the determinants of the following matrices. Then use the definition of a determinant to check your answers.

- Cofactor across the $i^{th}$ column: $det A: a_{i1}c_{i1} + \cdots a_{in}c_{in} $.

- Cofactor across the $j^{th}$ row: $det A: a_{1j}c_{1j} + \cdots a_{nj}c_{nj} $.

## Detrminants of $2 \times 2$ matrix

<br>

1. $ det \begin{vmatrix} 1&2\\ 4&4 \end{vmatrix} = 1\times 4 - 2 \times 4 =-4 $

<br>

2.  $ det \begin{vmatrix} 5&0\\ 0&6 \end{vmatrix} = 30 $

<br>

3.  $ det \begin{vmatrix} 0&8\\ 0&9 \end{vmatrix} = 0 $

<br>

4.  $ det \begin{vmatrix} 7&5\\ 0&0 \end{vmatrix} = 0 $

<br>

5.  $ det \begin{vmatrix} 3&x\\ 2&1 \end{vmatrix} = 3-2x $


## Detrminants of $3 \times 3$ matrix
<br>

6. $ det \begin{vmatrix} 1&2&3\\ 0&0&4\\5&6&7 \end{vmatrix} = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} = 0 +0 +4 \times (-1)^{(2+3)} \times  det \begin{vmatrix} 1&2\\ 5&6 \end{vmatrix} = -4 \times (6-10) = 16 $

<br>

7. $ det \begin{vmatrix} 2&0&-1\\ 3&4&1\\5&0&6 \end{vmatrix} = a_{12}c_{12} + a_{22}c_{22} + a_{32}c_{32} = 0 + 4 \times (-1)^{(2+2)} \times  det \begin{vmatrix} 2&-1\\ 5&6 \end{vmatrix} + 0  = 4 \times (12+5) = 68$

## Detrminants of high-D matrix
<br>

8. $ det \begin{vmatrix} 2&3&5&1\\ 7&0&1&-2\\-1&4&9&2\\3&1&0&4 \end{vmatrix} \\ = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} \\ = 7 \times (-1)^{(2+1)} \times det \begin{vmatrix} 2&5&1\\-1&9&2\\3&0&4 \end{vmatrix} + 0 + 1 \times (-1)^{(2+3)} \times det \begin{vmatrix} 2&3&1\\-1&4&2\\3&1&4 \end{vmatrix} +  2 \times (-1)^{(2+4)} \times det \begin{vmatrix} 2&3&5\\-1&4&9\\3&1&0 \end{vmatrix} \\ = -7 \times (2 \times (-1)^{(1+3)} \times det \begin{vmatrix} 5&1\\9&2 \end{vmatrix} + 4 \times (-1)^{(3+3)} \times det \begin{vmatrix} 2&5\\1&9 \end{vmatrix}) - (2 \times (-1)^{(1+1)} \times det \begin{vmatrix} 4&2\\1&4 \end{vmatrix}+ 3 \times (-1)^{(1+2)} \times det \begin{vmatrix} -1&2\\3&4 \end{vmatrix} + (-1)^{(1+3)} \times det \begin{vmatrix} -1&4\\3&1 \end{vmatrix})+ 2 \times (3 \times (-1)^{(1+3)} \times det \begin{vmatrix} 3&5\\4&9 \end{vmatrix} + (-1)^{(3+2)} \times det \begin{vmatrix} 2&5\\-1&9 \end{vmatrix}) \\ =-7 \times [(-2)+5\times 13] - [2\times 14 -3\times (-10)+-14] + 2\times[3\times 7-23]\\ = (-7)\times 63 - 44 -4 = -489 $ 

In [26]:
# check answers
LA.det(np.matrix([[2,3,5,1],
                 [7,0,1,-2],
                 [-4,1,9,2],
                 [3,1,0,4]]))

-742.0

9. $det \begin{vmatrix} 1&3&2&0&4\\7&9&0&4&1\\5&8&0&3&2\\1&5&7&0&6\\-1&3&2&1&5 \end{vmatrix}
= 2 \times det \begin{vmatrix} 7&9&4&1\\5&8&3&2\\1&5&0&6\\-1&3&1&5\end{vmatrix} - 7 \times det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\-1&3&1&5\end{vmatrix} + 2\times det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\1&5&0&6\end{vmatrix} \\
$

<br>

$det \begin{vmatrix} 7&9&4&1\\5&8&3&2\\1&5&0&6\\-1&3&1&5\end{vmatrix} = det \begin{vmatrix} 9&4&1\\8&3&2\\3&1&5 \end{vmatrix} - 5\times det \begin{vmatrix} 7&4&1\\5&3&2\\-1&1&5\end{vmatrix}  - 6\times det \begin{vmatrix} 7&9&4\\5&8&3\\-1&3&1\end{vmatrix}\\
= 9*3*8+4*2*3+1*8*2-4*8*5-1*2*9-1*3*1 - 5\times (7*3*5-4*2*1+1*5*2-4*5*5-1*2*7+1*3*1) - 6\times(7*8-3*9+4*5*3-5*9-3*3*7+4*8)\\
= 75 - 5\times (-4)-  6\times(13) \\
=13 $

<br>

$det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\-1&3&1&5\end
{vmatrix} \\
= det \begin{vmatrix} 9&4&1\\8&3&2\\-3&1&5\end{vmatrix} -3\times det \begin{vmatrix} 7&4&1\\5&3&2\\-1&1&5\end{vmatrix} - 4\times det \begin{vmatrix} 7&9&4\\5&8&3\\-1&3&1\end{vmatrix}\\
= (9*3*4-4*2*3+8-4*5*8-2*9+3*3)-3\times (7*3*5-4*2+5-4*5*5-2*7+3) - 4\times (7*8-3*9+4*5*5-5*9-3*3*7+4*8)\\
= -77 -3\times(-9) - 4\times(53)\\
=-262 $

<br>

$det \begin{vmatrix} 1&3&0&4\\7&9&4&1\\5&8&3&2\\1&5&0&6\end{vmatrix}\\
= -4\times det \begin{vmatrix} 1&3&4\\5&8&2\\1&5&6\end{vmatrix} + 3\times det \begin{vmatrix} 1&3&4\\7&9&1\\1&5&6\end{vmatrix}\\
= -4\times(8*6+3*2+4*5*5-3*6*5-2*5-4*8)+3\times(9*6+3+4*7*5-6*7*3-5-4*9)\\
=-4\times 22 + 3\times 30\\
=2$

<br>

Therefore , 
$det \begin{vmatrix} 1&3&2&0&4\\7&9&0&4&1\\5&8&0&3&2\\1&5&7&0&6\\-1&3&2&1&5 \end{vmatrix} = 2\times 13 -7\times(-262) +2\times2 = $


In [27]:
 round(LA.det(np.matrix([[1,3,2,0,4],
                 [7,9,0,4,1],
                 [5,8,0,3,2],
                 [1,5,7,0,6],
                 [-1,3,2,1,5]])),1)

213.0

# Properties of Inverse Matrices

---



Let $A$ and $B$ be 3 by 3 matrics such that $A = \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix}$, and $B = \begin{bmatrix} 1&2&1\\2&3&0\\1&3&0\end{bmatrix}$. 



<br>

## 1. Show that $(A^{-1})^{-1} = A$. 
<br>

$adj(A) =  \begin{bmatrix}  0 &(-1)\times (12-6)& 0\\(-1)\times (3-0)&24-18&(-1)\times (0-6)\\1&(-1)\times (8-12)& (0-4) \end{bmatrix} \prime  = \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4 \end{bmatrix} \prime = \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4 \end{bmatrix} $

<br>

$det(A) = 0+6+0 - 12 - 0-0 = -6$

<br>

$A^{-1} = \frac{1}{det(A)} adj(A) = (- \frac{1}{6}) \times \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4 \end{bmatrix} = \begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}  $

<br>

$adj(A^{-1}) = \begin{bmatrix}  -\frac{4}{3} &-\frac{2}{3}& -1\\-\frac{1}{6}&0&0 \\ -\frac{1}{2}&-\frac{1}{6}& - \frac{1}{2} \end{bmatrix} \prime = \begin{bmatrix}  -\frac{4}{3} &-\frac{1}{6}& -\frac{1}{2}\\-\frac{2}{3}&0&-\frac{1}{6} \\ -1 &0& - \frac{1}{2} \end{bmatrix} $

<br>

$det(A^{-1}) = \frac{1}{6}-(\frac{1}{3})=-\frac{1}{6}$

<br>

$(A^{-1})^{-1}= \frac{1}{det(A^{-1})}adj(A^{-1}) = (-6) \times \begin{bmatrix}  -\frac{4}{3} &-\frac{1}{6}& -\frac{1}{2}\\-\frac{2}{3}&0&-\frac{1}{6} \\ -1 &0& - \frac{1}{2} \end{bmatrix} =  \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix} =  A$

In [46]:
# check answer
A = np.matrix([[8,1,3],
              [4,0,1],
              [6,0,3]])
inv_A = LA.inv(A)

print("inv(A)= \n", 
      np.around(inv_A, decimals=3))

print("\n inv(inv(A))= \n", np.around(LA.inv(inv_A), decimals=3))

inv(A)= 
 [[-0.     0.5   -0.167]
 [ 1.    -1.    -0.667]
 [ 0.    -1.     0.667]]

 inv(inv(A))= 
 [[8. 1. 3.]
 [4. 0. 1.]
 [6. 0. 3.]]



## 2. Show that $(AB)^{-1}=B^{-1}A^{-1}$.

$AB = \begin{bmatrix} 8&1&3\\4&0&1\\6&0&3\end{bmatrix} \times \begin{bmatrix} 1&2&1\\2&3&0\\1&3&0\end{bmatrix} = \begin{bmatrix} 8+2+3&16+3+9&8\\4+1&8+3&4\\6+3&12+9&6\end{bmatrix} = \begin{bmatrix} 13&28&8\\5&11&4\\9&21&6\end{bmatrix}$

<br>

$det(AB) = 13*11*6 + 28*4*9 + 8*5*21 - 28*5*6 - 13*4*21-8*11*9 = -18$

<br>

$adj(AB) = \begin{bmatrix} 11*6-4*21&-(5*6-4*9)&21*5-9*11\\-(6*28-8*21)&6*13-9*8&-(21*13-9*28)\\4*28-8*11&-(4*13-5*8)&11*13-5*28\end{bmatrix} \prime \\
= \begin{bmatrix} -18&6&6\\0&6&-21\\24&-12&3\end{bmatrix} \prime = \begin{bmatrix} -18&0&24\\6&6&-12\\6&-21&3\end{bmatrix} $

<br>

$(AB)^{-1} = \frac{1}{det(AB)} adj(AB) = - \frac{1}{18} \times \begin{bmatrix} -18&0&24\\6&6&-12\\6&-21&3\end{bmatrix} = \begin{bmatrix} 1&0&- \frac{4}{3} \\- \frac{1}{3} &- \frac{1}{3} & \frac{2}{3} \\- \frac{1}{3} &\frac{7}{6} &- \frac{1}{6} \end{bmatrix}$


<br>
From #1 we have calculated that $A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$

<br>

$det(B) = 0+0+0-0-0-3 = 3$
$adj(B) = \begin{bmatrix} 0-0&-(0-0)&6-3\\-(0-3)&0-1&-(2-3)\\0-3&-(0-2)&3-4\end{bmatrix} \prime 
= \begin{bmatrix} 0&0&3\\3&-1&1\\-3&2&-1\end{bmatrix} \prime = \begin{bmatrix} 0&3&-3\\0&-1&2\\3&1&-1\end{bmatrix} $

<br>

$B^{-1} = \frac{1}{det(B)}adj(B) =  \frac{1}{3} \begin{bmatrix} 0&3&-3\\0&-1&2\\3&-1&-1\end{bmatrix} = \begin{bmatrix} 0&1&-1\\0&-\frac{1}{3} &\frac{2}{3} \\1&-\frac{1}{3} &-\frac{1}{3} \end{bmatrix} $

<br>

$B^{-1}A^{-1} = \begin{bmatrix} 0&1&-1\\0&-\frac{1}{3} &\frac{2}{3} \\1&-\frac{1}{3} &-\frac{1}{3} \end{bmatrix} \times \begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix} = \begin{bmatrix} 1&0&-\frac{4}{3}\\-\frac{1}{3} &-\frac{1}{3}&\frac{4}{3} \\-\frac{1}{3}&\frac{7}{6} &-\frac{1}{6} \end{bmatrix} = (AB)^{-1}$

In [45]:
B = np.matrix([[1,2,1],
               [2,3,0],
               [1,3,0]])
print("AB= \n", A*B)
print("\n inv(AB)= \n", np.round(LA.inv(A*B), decimals=2))
print("\n inv(B)inv(A)= \n", np.round(LA.inv(B)* LA.inv(A),decimals=2))

AB= 
 [[13 28  8]
 [ 5 11  4]
 [ 9 21  6]]

 inv(AB)= 
 [[ 1.   -0.   -1.33]
 [-0.33 -0.33  0.67]
 [-0.33  1.17 -0.17]]

 inv(B)inv(A)= 
 [[ 1.    0.   -1.33]
 [-0.33 -0.33  0.67]
 [-0.33  1.17 -0.17]]


## 3. Show that $(A\prime)^{-1}=(A^{-1})\prime$.
$A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$, $(A^{-1})\prime =\begin{bmatrix} 0&1&0\\\frac{1}{2}&-1& -1\\-\frac{1}{6}&-\frac{2}{3} &\frac{2}{3} \end{bmatrix}$. 

<br>

$A\prime = \begin{bmatrix} 8&4&6\\1&0&0\\3&1&3\end{bmatrix}$, $det(A\prime) = 6-12 = -6$

<br>

$adj(A\prime) = \begin{bmatrix} 0&-(3)&1\\-(12-6)&24-18&-(8-12)\\0&-(-6)&-4\end{bmatrix}\prime  = \begin{bmatrix} 0&-3&1\\-6&6&4\\0&6&-4\end{bmatrix}\prime = \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4\end{bmatrix}\prime $

<br>

$(A\prime)^{-1} = \frac{1}{det(A\prime)} adj(A\prime) = -\frac{1}{6} \times \begin{bmatrix} 0&-6&0\\-3&6&6\\1&4&-4 \end{bmatrix} = \begin{bmatrix} 0&1&0\\\frac{1}{2}&-1& -1\\-\frac{1}{6}&-\frac{2}{3} &\frac{2}{3} \end{bmatrix}$.

<br>

$(A\prime)^{-1}=(A^{-1})\prime$ is thus proven.

In [42]:
print("(A_inv)transpose = \n", np.round(LA.inv(A).T, decimals = 2))

print("\n (A_transpose)inv = \n", np.round(LA.inv(A.T), decimals=2))

(A_inv)transpose = 
 [[-0.    1.    0.  ]
 [ 0.5  -1.   -1.  ]
 [-0.17 -0.67  0.67]]

 (A_transpose)inv = 
 [[ 0.    1.    0.  ]
 [ 0.5  -1.   -1.  ]
 [-0.17 -0.67  0.67]]


## 4. Show that $det(A^{-1}) = \frac{1}{det(A)}$.

<br>

From #1, we get $det(A) = 0+6+0 - 12 - 0-0 = -6$. 

<br>

From #3, we get $A^{-1}=\begin{bmatrix} 0&\frac{1}{2}&-\frac{1}{6}\\1&-1& -\frac{2}{3}\\0&-1&\frac{2}{3} \end{bmatrix}$. We can then calculate $det(A^{-1})= \frac{1}{6} - \frac{1}{3} = -\frac{1}{6}$.

<br>

$det(A^{-1}) = \frac{1}{det(A)}$ is thus proven.
 

## 5. 

Let $C$ be a 3 by 3 matrix such that $C = \begin{bmatrix} 6&2&4\\0&2& 1\\0&0&3 \end{bmatrix}$. Find the inversion of $C$ and verify that it is a triagular matrix. 

A triangular matrix is one that is either lower triangular or upper triangular.

<br>

$det(C) = 6*2*3 - 0 =36$ 

<br>

$adj(C) = \begin{bmatrix} 6&-0&0\\-6&18&-0\\2-8&-6&12 \end{bmatrix} \prime  = \begin{bmatrix} 6&0&0\\-6&18&0\\-6&-6&12 \end{bmatrix} \prime =  \begin{bmatrix} 6&-6&-6\\0&18&-6\\0&0&12 \end{bmatrix}  $

<br>

$C^{-1} = \frac{1}{det(C)} adj(C) = \frac{1}{36} \times \begin{bmatrix} 6&-6&-6\\0&18&-6\\0&0&12 \end{bmatrix} = \begin{bmatrix} \frac{1}{6}&-\frac{1}{6}&-\frac{1}{6}\\0&\frac{1}{2}&-\frac{1}{6}\\0&0&\frac{1}{3} \end{bmatrix}$

<br>

C is shown as a lower triangular matrix.

In [48]:
C = np.matrix([[6,2,4],
               [0,2,1],
               [0,0,3]])
LA.det(C)
LA.inv(C)

matrix([[ 0.16666667, -0.16666667, -0.16666667],
        [ 0.        ,  0.5       , -0.16666667],
        [ 0.        ,  0.        ,  0.33333333]])

# Matrix Inversion

## I. Find the inverses of the following matrices, if they exist. Use Mathematica to check your answers.

<br>

1. $\begin{bmatrix}1&2\\3&4\end{bmatrix}$
$$det = 4-6 = -2$$

$$adj = \begin{bmatrix}4&-3\\-2&1\end{bmatrix}$$

$$(\begin{bmatrix}1&2\\3&4\end{bmatrix})^{-1} = -\frac{1}{2} \times \begin{bmatrix}4&-3\\-2&1\end{bmatrix} = \begin{bmatrix}-2&1.5\\1&-0.5 \end{bmatrix}$$

<br>

2. $\begin{bmatrix}5&0\\0&6\end{bmatrix}$

$$det = 30-0 = 30$$

$$adj = \begin{bmatrix}6&0\\0&5\end{bmatrix}$$

$$(\begin{bmatrix}5&0\\0&6\end{bmatrix})^{-1} = \frac{1}{30} \times \begin{bmatrix}6&0\\0&5 \end{bmatrix} = \begin{bmatrix} \frac{1}{5}&0\\0&\frac{1}{6} \end{bmatrix}$$

<br>

3. $\begin{bmatrix}0&8\\0&9\end{bmatrix}$

$det =0$, the matrix is not of full rank and thus not inversable. 

<br>

4. $\begin{bmatrix}7&5\\0&0\end{bmatrix}$

$det =0$, the matrix is not of full rank and thus not inversable. 

<br>

5. $\begin{bmatrix}3&x\\2&1\end{bmatrix}$

$$det = 3-2x$$

$$adj = \begin{bmatrix}1&-2\\-3&x \end{bmatrix}$$

$$(\begin{bmatrix}3&x\\2&1\end{bmatrix})^{-1} = \frac{1}{3-2x} \times \begin{bmatrix}1&-2\\-3&x \end{bmatrix} = \begin{bmatrix} \frac{1}{3-2x}&-\frac{2}{3-2x}\\-\frac{3}{3-2x}&\frac{x}{3-2x}\end{bmatrix}$$

<br>

6. $\begin{bmatrix}1&2&3\\0&0&4\\5&6&7 \end{bmatrix}$

$$det = 2\times 4 \times5 - 1\times 6\times 4 = 16$$

$$adj = \begin{bmatrix}-24&-(-20)&0\\-(14-18)&7-15&-(6-10)\\8&-(4)&0 \end{bmatrix} \prime = \begin{bmatrix}-24&20&0\\-4&-8&4\\8&-4&0 \end{bmatrix} \prime = \begin{bmatrix}-24&-4&8\\20&-8&-4\\0&-4& 0\end{bmatrix}$$

$$(\begin{bmatrix}1&2&3\\0&0&4\\5&6&7 \end{bmatrix})^{-1} = \frac{1}{16} \times \begin{bmatrix}-24&-4&8\\20&-8&-4\\0&-4& 0\end{bmatrix} =  \begin{bmatrix}-1.5&-0.25&0.5\\1.25&-0.5&-0.25\\0&-0.25&0\end{bmatrix}$$

7. $\begin{bmatrix}2&0&-1\\3&4&1\\5&0&6 \end{bmatrix}$

$$det = -4*5-2*4*6 = -68$$

$$adj = \begin{bmatrix}24&-(18-5)&-20\\-(0)&12-(-5)&-(0)\\0-(-4)&-(2-(-3))&8 \end{bmatrix} \prime = \begin{bmatrix}24&-23&-20\\0&17&0\\4&-5&8 \end{bmatrix} \prime = \begin{bmatrix}24&0&4\\-23&17&-5\\-20&0&8 \end{bmatrix}$$

$$(\begin{bmatrix}2&0&-1\\3&4&1\\5&0&6 \end{bmatrix})^{-1} = -\frac{1}{68} \times \begin{bmatrix}24&0&4\\-23&17&-5\\-20&0&8 \end{bmatrix} = \begin{bmatrix} -\frac{6}{17} &0&-\frac{1}{17} \\\frac{23}{68} &\frac{1}{4}&\frac{5}{68}\\\frac{5}{17}&0&- \frac{2}{17} \end{bmatrix}$$

<br>

8. $\begin{bmatrix}1&2&3\\1&3&6\\1&4&10 \end{bmatrix}$

$$det =3*10+ 2*6+ 3*4-2*10-4*6-3*3= 20+12+12-20-24-9 = 1$$

$$adj = \begin{bmatrix}30-24&-(10-6)&4-3\\-(20-12)&10-3&-(4-2)\\12-9&-(6-3))&3-2 \end{bmatrix} \prime = \begin{bmatrix}6&-4&1\\-8&7&-2\\3&-3&1 \end{bmatrix} \prime = \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix}$$

$$(\begin{bmatrix}1&2&3\\1&3&6\\1&4&10 \end{bmatrix})^{-1} = 1\times \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix} = \begin{bmatrix}6&-8&3\\-4&7&3\\1&-2&1 \end{bmatrix}$$


In [12]:
print("6. \n", LA.inv(np.matrix([[1,2,3],
          [0,0,4],
           [5,6,7]])))

print("\n 7. \n", LA.inv(np.matrix([[2,0,-1],
                  [3,4,1],
                  [5,0,6]])))

print("\n 8. \n", LA.inv(np.matrix([[1,2,3],
                  [1,3,6],
                  [1,4,10]])))

6. 
 [[-1.5   0.25  0.5 ]
 [ 1.25 -0.5  -0.25]
 [ 0.    0.25  0.  ]]

 7. 
 [[ 0.35294118  0.          0.05882353]
 [-0.19117647  0.25       -0.07352941]
 [-0.29411765 -0.          0.11764706]]

 8. 
 [[ 6. -8.  3.]
 [-4.  7. -3.]
 [ 1. -2.  1.]]


## II. Solve the following systems of equations by using matrices. Use Mathematica to check your answers.

<br>

9. $2x-3y =2\\4x+y=5$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}2\\5 \end{bmatrix}$.   

$$ \begin{aligned}
\begin{bmatrix}x\\y \end{bmatrix} 
&= (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}2\\5 \end{bmatrix}\\ 
&= \frac{1}{2*1 - 4*(-3)} \times \begin{bmatrix}1&-4\\3&2 \end{bmatrix} \prime \times \begin{bmatrix}2\\5 \end{bmatrix}  \\ &=  \frac{1}{14} \times \begin{bmatrix}1&3\\-4&2 \end{bmatrix} \times \begin{bmatrix}2\\5 \end{bmatrix} \\
&=  \frac{1}{14} \times \begin{bmatrix}1*2+3*5\\-4*2+2*5 \end{bmatrix}\\
&=  \frac{1}{14} \times \begin{bmatrix}17\\2 \end{bmatrix}\\
&= \begin{bmatrix}\frac{17}{14}\\ \frac{1}{7} \end{bmatrix} \end{aligned}
$$ 

Thus, $x=\frac{17}{14}, y = \frac{1}{7} $

<br>

10. $2x-3y=0\\4x+y=3$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}0\\3 \end{bmatrix}$.  

$$ \begin{aligned}
\begin{bmatrix}x\\y \end{bmatrix} 
&= (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}0\\3 \end{bmatrix}\\ 
&=  \frac{1}{14} \times \begin{bmatrix}1&3\\-4&2 \end{bmatrix} \times \begin{bmatrix}0\\3 \end{bmatrix} \\
&=  \frac{1}{14} \times \begin{bmatrix}9\\6 \end{bmatrix}\\
&= \begin{bmatrix}\frac{9}{14}\\ \frac{3}{7} \end{bmatrix} \end{aligned}$$

Therefore, $x=\frac{9}{14}, y = \frac{3}{7} $
 

<br>

11. $2x-3y=0\\4x+y=0$

The linear equations expressee in matrix form is $ \begin{bmatrix}2&-3\\4&1 \end{bmatrix} \times \begin{bmatrix}x\\y \end{bmatrix} = \begin{bmatrix}0\\0 \end{bmatrix}$. Thus $ \begin{bmatrix} x\\y \end{bmatrix} = (\begin{bmatrix}2&-3\\4&1 \end{bmatrix})^{-1} \times \begin{bmatrix}0\\0 \end{bmatrix} = \begin{bmatrix}0\\0 \end{bmatrix} $. Therefore, $x=y=0$

<br>

12. $-3x_{1}- x_{2}-3x_{3}=1 \\ 6x_{1}+x_{2}+3x_{3}=0 \\ 2x_{1}+x_{3}=1$

The linear equations expressee in matrix form is $ \begin{bmatrix}-3&-1&-3\\6&1&3\\2&0&1 \end{bmatrix} \times \begin{bmatrix}x_{1}\\x_{2}\\x_{3} \end{bmatrix} = \begin{bmatrix}1\\0\\1 \end{bmatrix}$.

$$ \begin{aligned}
\begin{bmatrix} x_{1}\\x_{2}\\x_{3} \end{bmatrix} 
&= (\begin{bmatrix}-3&-1&-3\\6&1&3\\2&0&1 \end{bmatrix})^{-1} \times \begin{bmatrix}1\\0\\1 \end{bmatrix}\\ 
&=  \frac{1}{-3-6+0-(-6)-0-(-6)} \times \begin{bmatrix}1&-(0)&-2\\-(-1)&-3-6&-(0-(-2))\\-3-(-3)&-(-9-(-18))&-3-(-6) \end{bmatrix} \prime \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&=  \frac{1}{3} \times \begin{bmatrix}1&0&-2\\1&3&-2\\0&-9&3 \end{bmatrix} \prime \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&= \frac{1}{3} \times \begin{bmatrix}1&1&0\\0&3&-9\\-2&-2&3 \end{bmatrix} \times \begin{bmatrix}1\\0\\1 \end{bmatrix} \\
&= \frac{1}{3} \times \begin{bmatrix}1\\-9\\1 \end{bmatrix}
\\ 
&= \begin{bmatrix}\frac{1}{3}\\-3\\\frac{1}{3} \end{bmatrix}
\end{aligned}$$

Therefore, $x_{1}=frac{1}{3},  x_{2}=-3, x_{3}=frac{1}{3}$.

In [13]:
print("9. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[2],
                                              [5]]))

print("\n 10. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[0],
                                              [3]]))

print("\n 11. \n", 
      LA.inv(np.matrix([[2,-3],
                        [4,1]])) * np.matrix([[0],
                                              [0]]))

print("\n 12. \n", 
      LA.inv(np.matrix([[-3,-1,-3],
                        [6,1,3],
                        [2,0,1]])) * np.matrix([[1],
                                                [0],
                                                [1]]))

9. 
 [[1.21428571]
 [0.14285714]]

 10. 
 [[0.64285714]
 [0.42857143]]

 11. 
 [[0.]
 [0.]]

 12. 
 [[ 0.33333333]
 [-3.        ]
 [ 0.33333333]]


matrix([[ 0.33333333,  0.33333333,  0.        ],
        [-0.        ,  1.        , -3.        ],
        [-0.66666667, -0.66666667,  1.        ]])

# Rank of a Matrix